### ISSUE TITLE
Nuxt apollo only loading data after page refresh

### ISSUE THREAD

**Issue by ImreC** [nuxt-community/apollo-module#102]
I am currently experimenting with the apollo module and have retrieved data from my backend succesfully using the following settings:

```
apollo: {
  products: {
    query: products,
    variables: {
      limit: 10
    },
    prefetch: true
  }
},

```
However, this only seems to work when refreshing the page and not when changing routes. How do I get this to work while changing routes?

**Comment by ImreC** [comment]
Ok, after implementing the client in the asyncData method I found that I was getting an error which seemed to have something to do with my token settings. Changed those. After that it looked like I had a CORS issue. Fixed that. Now it's working. Two remarks. 1) I was able to get data from my API with the CORS settings being wrong. I don't understand that. 2) There was no error handling in the apollo object that could have led me to this conclusion.

**Comment by dohomi** [comment]
@ImreC this plugin only supersets `vue-apollo` and on the long run `apollo` for your Nuxt project. It seems to me that you might did some misconfiguration passing the right token at the right time.
You can add your error handling inside of your config:
```
import {onError} from 'apollo-link-error'

export default (context) => {
 (..)
const errorLink = onError((res) => {
    const {graphQLErrors, networkError} = res
    if (graphQLErrors) {
      graphQLErrors.map(({message, locations, path}) =>
        console.log(
          `[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`
        )
      )
    }
    if (networkError) console.log(`[Network error]: ${networkError}`)
  })

  // return the an object with additional apollo-client options
  return {
    link: from([errorLink, authMiddleware, link]),
    cache: new InMemoryCache()
  }
}

**Comment by ImreC** [comment]
Yeah, my token settings weren't working. I have added the error handling part. Thanks for the help! It is difficult to figure things out since the solution to your woes lies in either the apollo-client, vue-apollo or nuxt-apollo docs. Maybe I'll try to do a tutorial if I get the hang of this a little bit more.
