### ISSUE TITLE
Store cache issue

### ISSUE THREAD

**Issue by Nainterceptor** [nuxt-community/apollo-module#11]
Hello,

I have an issue, when I have routes with nuxt child, I've a cache fail on parent routes. You can see the issue here : https://github.com/Nainterceptor/nuxt.js/tree/issue/store-cache/examples/vue-apollo (or live in https://nuxt-vue-apollo-elszaxsupq.now.sh).

I'm on the homepage, I click on a car, I refresh, then I click on another car, the main list disappear.

I'm trying to find the issue without sucess (And of course it's working when I disable cache)

Thanks for your help !

**Comment by dohomi** [comment]
@Nainterceptor you still face this issue?

**Comment by dohomi** [comment]
Closing this issue for now, feel free to open it again in case you are still facing the issue

**Comment by Nainterceptor** [comment]
Hello, issue still here, I've updated the now.sh link, steps to reproduce are the same.

**Comment by Nainterceptor** [comment]
@dohomi I'm not able to reopen this issue, can you do it ?
Thanks

**Comment by dohomi** [comment]
@Nainterceptor is it possible that your issue is related to this issue: https://github.com/Akryum/vue-apollo/issues/127

**Comment by Nainterceptor** [comment]
Possible, I'll try your workaround tomorrow, thanks

**Comment by Nainterceptor** [comment]
I've tried to do check if I've a timing issue like you, but in the following exemple, when the list is missing, result is just not called. So seems to be a different issue.

```js
export default {
  data() {
    return {
      allCars: [],
    };
  },
  apollo: {
    allCars: {
      prefetch: true,
      query: allCars,
      manual:true,
      result({data}){
        console.log('triggered'); // Weird console.log, but easier to explain :)
        console.log('before', data);
        this.$nextTick(() => {
        console.log('after', data);
          this.allCars = data.allCars;
        });
      }
    }
  },
  head: {
    title: 'Cars with Apollo'
  }
};
```

**Comment by dohomi** [comment]
@Nainterceptor you better of asking this in the official `vue-apollo` package. The issue you are facing seems to be some generic SSR apollo caching issue

**Comment by dohomi** [comment]
@Nainterceptor can you check it with upgraded v3 of this module? Please make sure to read the upgrade-guide.

**Comment by Nainterceptor** [comment]
Hello, FYI, issue still here after migrated, I'll report bug to vue-apollo.

**Comment by ikey2244** [comment]
Is there any update on this? I am having issues.

**Comment by NMathar** [comment]
I had the same problem today and i had thos problem when child and parent query attributes are not identical
