### ISSUE TITLE
Use of apollo-error-link with version 4?

### ISSUE THREAD

**Issue by aldarund** [nuxt-community/apollo-module#115]
How to add use of apollo-error-link with version 4 ?
In version 3 i was having this:
```
const errorLink = onError(({ graphQLErrors, networkError }) => {
    if (networkError) {
      ctx.app.$messages.showErrorMessage(networkError.message)
    }
    if (graphQLErrors) {
      graphQLErrors.map(({ message }) =>
        ctx.app.$messages.showErrorMessage(message)
      )
    }
  })
  const link = middlewareLink.concat(errorLink).concat(httpLink)
  return {
    link,
    cache: new InMemoryCache()
  }
```
I dont see how can i add onError handler for version 4 of plugin.

PS asked on cmty as question ( https://cmty.app/nuxt/apollo-module/issues/c93 ) but it doesnt import into github and i didnt see any replied to any questions that is solely on cmty without github, so it made me think that its not monitored at all..

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c97">#c97</a>)</em></sub></div>

**Comment by dohomi** [comment]
@aldarund seems that currently there is no option to set in in https://github.com/Akryum/vue-cli-plugin-apollo/blob/master/graphql-client/src/index.js

Open an issue there if you rely `onError` - all configuration option from that plugin will be available here.

**Comment by dohomi** [comment]
@aldarund I will close the issue here. Please open a ticket on `vue-cli-plugin-apollo` as soon the option is available there I will provide its functionality in this package as well
