### ISSUE TITLE
apollo-module.js: Duplicate declaration "currentOptions"

### ISSUE THREAD

**Issue by Musbell** [nuxt-community/apollo-module#118]
Module build failed: Duplicate declaration "currentOptions"

  54 |   
  55 |       // Create apollo client
> 56 |       const currentOptions = {
     |             ^
  57 |   "httpEndpoint": "http://localhost:5000",
  58 |   "wsEndpoint": "ws://localhost:5000",
  59 |   "tokenName": "apollo-token"

**Comment by dohomi** [comment]
@Musbell did you try beta.5?

**Comment by Musbell** [comment]
@dohomi I am using the latest version. Right now i am getting this Nuxt error when i run dev:

 ERROR  Nuxt error

  TypeError: Cannot convert undefined or null to object
  
  - Function.keys
  
  - module.js:9 ModuleContainer.module.exports
    [Jobcool-Nuxt]/[@nuxtjs]/apollo/lib/module.js:9:14
  
  - module.js:162 Promise
    [Jobcool-Nuxt]/[nuxt]/lib/core/module.js:162:30
  
  - new Promise
  
  - module.js:146 ModuleContainer.addModule
    [Jobcool-Nuxt]/[nuxt]/lib/core/module.js:146:12
  
  - utils.js:96 promise.then
    [Jobcool-Nuxt]/[nuxt]/lib/common/utils.js:96:43
  
  
  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7
  
  - module.js:695 Function.Module.runMain
    module.js:695:11
  
  - bootstrap_node.js:188 startup
    bootstrap_node.js:188:16
  
  - bootstrap_node.js:609 
    bootstrap_node.js:609:3

**Comment by dohomi** [comment]
Please show a reproduction of your issue. Without that I'm unable to help

**Comment by Musbell** [comment]
@dohomi  thanks for your quick response. it is now fixed after upgrading vuetify to the latest version '1.0.19'
