### ISSUE TITLE
mutation not working with Client state ( apollo-link-state) configuration

### ISSUE THREAD

**Issue by gbouteiller** [nuxt-community/apollo-module#119]
Hello,
I'm trying to use the module with **apollo-link-state** in order to replace **vuex** with **graphql**. I can query from the cache but when I try to mutate, I get a warning : `Missing field updateColor in {}`.
```js
/** package.json **/

{
  "name": "apollo",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "dev": "nuxt"
  },
  "dependencies": {
    "@nuxtjs/apollo": "^4.0.0-beta.5",
    "graphql-tag": "^2.9.2",
    "nuxt": "^1.4.1"
  }
}
```

```js
/** nuxt.config.js **/

  apollo: {
    clientConfigs: {
      default: {
        clientState: {
          defaults: {
            color: 'red',
          },
          resolvers: {
            Mutation: {
              updateColor: (_, { color }, { cache }) => {
                const data = { color };
                cache.writeData({ data });
                return data;
              },
            },
          },
        },
        httpEndpoint: 'http://localhost:4000', //not used but required
      },
    },
  },
  modules: ['@nuxtjs/apollo'],
};
```

```vue
/** pages/index.vue **/

<template>
  <div>
    <h1>{{color}}</h1>
    <button @click="updateColor">Update</button>
  </div>
</template>

<script>
  import gql from 'graphql-tag';

  export default {
    apollo: {
      color: gql`
        query {
          color @client
        }
      `
    },
    methods: {
      updateColor: function() {
        this.$apollo.mutate({
          mutation: gql`
            mutation($color: String!) {
              updateColor(color: $color) @client
            }
          `,
          variables: { color: 'green' },
        });
      }
    }
  }
</script>
```
If I replace **apollo-module** by the **vue-apollo** plugin with `ssr: false`, it works.
Any help would be appreciated. Thank you.

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c102">#c102</a>)</em></sub></div>

**Comment by gbouteiller** [comment]
After investigation, it is due to : 
```js
/** @nuxtjs/apollo/lib/templates/plugin.js : l.18 **/

var currentOptions = <%= JSON.stringify(options.clientConfigs[key], null, 2) %>
```

In fact, options are stringified so every function inside is removed. That's why `updateColor` doesn't exist.  Consequently, the problem isn't only for client state but every function defined in options.

**Comment by dohomi** [comment]
@gbouteiller thats an interesting case: I fixed one issue in one of the beta releases as you can see here: https://github.com/nuxt-community/apollo-module/blob/master/lib/templates/plugin.js#L22 It would be interesting to know if you would replace 
```js
var currentOptions = <%= JSON.stringify(options.clientConfigs[key], null, 2) %>
to
var currentOptions = eval(<%= options.clientConfigs[key] %>)
```

**Comment by gbouteiller** [comment]
@dohomi it outputs 
```
Syntax Error: SyntaxError: C:/Coding/Nuxt/apollo/.nuxt/apollo-module.js: Unexpected token, expected , (20:40)
```

**Comment by dohomi** [comment]
@gbouteiller I published a new release https://github.com/nuxt-community/apollo-module/releases/tag/v4.0.0-beta.6 Now you should be able to provide a path to your config. Does it fix your current issues?

**Comment by gbouteiller** [comment]
@dohomi it works like a charm!! Thank you for your dedication and great work!
