### ISSUE TITLE
How to add custom options to ApolloClient

### ISSUE THREAD

**Issue by dre1080** [nuxt-community/apollo-module#12]
Is it possible to add custom options to ApolloClient such as [`queryDeduplication`](http://dev.apollodata.com/core/network.html#query-deduplication)?

**Comment by jamilabreu** [comment]
similarly as a heads up, replacing `createNetworkInterface` with `createBatchingNetworkInterface` seems to break things:

```
import { createBatchingNetworkInterface } from 'apollo-client'

export default createBatchingNetworkInterface({
  uri: 'http://localhost:4000/api'
})
```

**Comment by bjunc** [comment]
Also, check out our discussion regarding auth headers in #5.  The TL;DR is using a Nuxt middleware to tap into the Apollo middleware.
