### ISSUE TITLE
I keep getting Mismatching childNodes vs. VNodes with v-for

### ISSUE THREAD

**Issue by kieusonlam** [nuxt-community/apollo-module#125]
### Version

[v4.0.0-beta.7](https://github.com/apollo-module/releases/tag/v4.0.0-beta.6)

### Reproduction link

[https://github.com/nuxt-community/apollo-module](https://github.com/nuxt-community/apollo-module)

### Steps to reproduce

It's happen on my 2 project. I just using normal code.

```js
<template>
    <div>
        <div>Something</div>
        <div v-for="post in posts" :key="post.id">
            {{ post.title }}
        </div>
        <div>Something else</div>
    </div>
</template>

<script>
export default {
  data: () => ({
    posts: null
  }),
  apollo: {
    posts: {
      query: postsQuery,
      variables: { first: 25 },
      prefetch: true
    }
  }
}
</script>
```
When I add any tag before or after "v-for" tag I got "Mismatching childNodes vs. VNodes".

![mismatch.JPG](https://cmty.s3.eu-west-1.amazonaws.com/98543958/928d9590-84f0-11e8-927c-816d6e74c27b.JPG)

And sometime if I remove both those tag I got duplicated results.

![duplication.JPG](https://cmty.s3.eu-west-1.amazonaws.com/98543958/666f0750-84f0-11e8-927c-816d6e74c27b.JPG)

### What is expected ?

Working normaly.

### What is actually happening?

"Mismatching childNodes vs. VNodes" and "Duplicated results"

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c108">#c108</a>)</em></sub></div>

**Comment by kieusonlam** [comment]
I wonder is there anyone get the same problem or just me?

**Comment by dohomi** [comment]
I honestly don't use `prefetch:true` in my app so I can't tell. If you have a reproduction to trace down the error would be perfect

**Comment by dohomi** [comment]
before I forget: is this new or happened on other versions as well?

**Comment by kieusonlam** [comment]
I not quire sure when it's happened, as I remember it used to work.

 And yes I did try some older version, still got the same problem.

Here is the repo: https://github.com/kieusonlam/apollo-module-issue-125

I did try to replace prefetch with asyncData
```js
  async asyncData({ app }){
    const posts= await app.apolloProvider.defaultClient.query({
       ...
    }).then(({ data }) => data && data.posts)
    return { posts }
  },
  data: () => ({
    posts: []
  }),
  apollo: {
    movies: {
        ...
    }
  }
```

In some place it's work, in some place it's not @_@

By the way if I view source of the web page, I can see that SSR is render correctly, and also what i tried with asyncData, I think maybe it is a client side problem?

**Comment by kieusonlam** [comment]
My bad, I can reconfirm that asyncData is work as the replacement.

**Comment by dohomi** [comment]
@kieusonlam for me this sounds like an issue rather on Nuxt or vue-apollo than this wrapper. To overcome SSR issues I mostly use your `asyncData` approach to make sure that everything is fetched on the server.

**Comment by kieusonlam** [comment]
Think you right. 

I feel like `prefetch` is better `asyncData` for some case. For me sometime the api server can take long time to response, so the vistor have to wait for the data until go to the next page. With prefetch, I can take visitor to the next page faster with the loading placeholder on components. I feel like it's much better for UX.

It would be nice if someone can fix it. I will close this issue for now. Thanks @dohomi

**Comment by kieusonlam** [comment]
Hey @dohomi 

Just wanna let you know, I just tried my old code, it's weird because it's working without problem. https://github.com/kieusonlam/apollo-module

**Comment by dohomi** [comment]
then there must be a bug :-) can you diff the current plugin with your fork and see what might be the issue? All I'd think of is the getAuth function might differs on server to client - that might result in the render issue. Lets say you have on server different credentials than on client than both requests will deliver different result and so the render will be different as well

**Comment by kieusonlam** [comment]
I created a PR https://github.com/nuxt-community/apollo-module/pull/126
