### ISSUE TITLE
Allow for relative path in httpEndpoint configuration

### ISSUE THREAD

**Issue by hoon-dialog** [nuxt-community/apollo-module#131]
### What problem does this feature solve?

The httpEndpoint configuration property must be specified with an absolute path at time of build.

This change will allow this to be done at runtime, note it depends on https://github.com/nuxt-community/apollo-module/issues/130 being implemented as well.

### What does the proposed changes look like?

In module.js:24

    } else if (typeof clientConfig.httpEndpoint !== 'string' || !IS_LINK_RE.test(clientConfig.httpEndpoint)) {

Replace with

    } else if ((typeof clientConfig.httpEndpoint !== 'string' || !IS_LINK_RE.test(clientConfig.httpEndpoint))
          && typeof clientConfig.transformConfig !== 'function') {

In plugin.js:60

    if (typeof <%= key %>ClientConfig.transformConfig === 'function') {
      <%= key %>ClientConfig = <%= key %>ClientConfig.transformConfig(<%= key %>ClientConfig);
    }
 
    // Create apollo client

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c116">#c116</a>)</em></sub></div>

**Comment by dohomi** [comment]
@hoon-dialog please read the comments of your previous issue. I think using a path to your config will solve the issue if I'm understanding your usecase right.

**Comment by hoon-dialog** [comment]
@dohomi Thanks for that. I have followed your suggestion and I can make it work for me as it does execute at runtime. However, the process.env variables set in my .env file are not propagating. Are these expected to be persisted? I assumed these were only available at _build time_.

**Comment by hoon-dialog** [comment]
@dohomi I had to export the process.env.HTTP_ENDPOINT in my nuxt.config.js and use the context variable instead of process.
