### ISSUE TITLE
Auth issue with multiple clients

### ISSUE THREAD

**Issue by timhanlon** [nuxt-community/apollo-module#132]
### Version

[v4.0.0-rc.0](https://github.com/apollo-module/releases/tag/v4.0.0-rc.0)

### Reproduction link

[https://gist.github.com/timhanlon/58822149b6c528ad42b8e44fd9762f81](https://gist.github.com/timhanlon/58822149b6c528ad42b8e44fd9762f81)

### Steps to reproduce

Both client configs and the generated `apollo-module.js` are in this gist: https://gist.github.com/timhanlon/58822149b6c528ad42b8e44fd9762f81

In the generated `apollo-module.js`, `defaultGetAuth` is being defined twice, once for each client.

It's causing this error: `ReferenceError: defaultTokenName is not defined`.

If I change the first definition of `defaultGetAuth` in the generated `apollo-module.js` to `gamesGetAuth`, and then change:

```
      if (!gamesClientConfig.getAuth) {
        gamesClientConfig.getAuth = defaultGetAuth
      }
```

to:

```
      if (!gamesClientConfig.getAuth) {
        gamesClientConfig.getAuth = gamesGetAuth
      }
```

...then things work as expected.

### What is expected ?

Both clients function

### What is actually happening?

ReferenceError: defaultTokenName is not defined

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c118">#c118</a>)</em></sub></div>

**Comment by dohomi** [comment]
@timhanlon I just released the PR thanks
