### ISSUE TITLE
Example project for apolllo-link-state with nuxt

### ISSUE THREAD

**Issue by DanielLourie** [nuxt-community/apollo-module#138]
### What problem does this feature solve?

Docs/config for setting up apollo-link-state with nuxt

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c122">#c122</a>)</em></sub></div>

**Comment by ameistad** [comment]
I have an example repo demonstrating this: [https://github.com/ameistad/nuxt-apollo-link-state](https://github.com/ameistad/nuxt-apollo-link-state)

Also, check out my [blog post](https://www.meidev.co/blog/nuxt-and-state-management-with-apollo-link-state-how-to-ditch-vuex) describing the steps.

I will try to make a PR in the near fututre.

**Comment by Und3Rdo9** [comment]
I tried to get your repository to work but several missings dependency errors came up. I'm currently trying to figure out how to make clientState work in combination with an external GQL endpoint but apollo dev tools is not picking up on the schema: 
```
clientConfigs: {
      default: {
        httpEndpoint: 'https://someexternalgql.com'
      },
      local: {
        httpEndpoint: 'http://localhost:4000', // not used but needed?
        typeDefs: localSchema,
        resolvers: localResolvers,
        onCacheInit: cache => {
          const data = {
            connected: false
          }
          cache.writeData({ data })
        }
      }
    }
```
I also tried putting all config in `local.clientState` but that doesn't work either and gives clientState property has been deprecated notice.

Any examples on how to mix local and remote schema's?

**Comment by vinstah** [comment]
I was able to get this working by using the typeDefs and resolvers parameters in my default client
`import gql from 'graphql-tag'
import { resolvers } from './local'

export default (context) => {
  return {
    // required
    httpEndpoint: process.env.GRAPHQL_HTTP,
    // optional
    // See https://www.apollographql.com/docs/link/links/http.html#options
    httpLinkOptions: {
      credentials: 'same-origin',
    },
    // You can use `wss` for secure connection (recommended in production)
    // Use `null` to disable subscriptions
    wsEndpoint: context.isDev ? null : process.env.GRAPHQL_WS, // optional
    // LocalStorage token
    tokenName: 'apollo-token', // optional
    // Enable Automatic Query persisting with Apollo Engine
    persisting: false, // Optional
    // Use websockets for everything (no HTTP)
    // You need to pass a `wsEndpoint` for this to work
    websocketsOnly: false, // Optional
    resolvers: resolvers,
    typeDefs: gql`
      type Query {
        hello: String
      }
    `,
  }
}
`

**Comment by kieusonlam** [comment]
Here is the local state example if anyone interest: https://github.com/nuxt-community/apollo-module/tree/master/test/fixture-local-state

I'll close this for now.
