### ISSUE TITLE
Set expiration date of cookie

### ISSUE THREAD

**Issue by timhanlon** [nuxt-community/apollo-module#142]
### What problem does this feature solve?

Cookies set by the `onLogin` helper do not expire.

`js-cookie` supports setting the number of days before expiry like this: `Cookies.set('name', 'value', { expires: 7 });`.

### What does the proposed changes look like?

A `tokenExpires` or `cookieExpires` option in `clientConfigs`, which is passed to `js-cookie`.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c127">#c127</a>)</em></sub></div>

**Comment by dohomi** [comment]
@timhanlon sounds like a good idea to me. I won't have time the following two weeks to work on any features but happy to receive PR's

**Comment by kieusonlam** [comment]
I exact what I need too :) PR https://github.com/nuxt-community/apollo-module/pull/143

**Comment by dohomi** [comment]
feature is merged
