### ISSUE TITLE
Problem with Nuxt Apollo with clientState

### ISSUE THREAD

**Issue by chanlito** [nuxt-community/apollo-module#144]
### Version

[v4.0.0-rc.1](https://github.com/apollo-module/releases/tag/v4.0.0-rc.1)

### Reproduction link

[https://github.com/chanlito/nuxt-apollo-link-state-bug](https://github.com/chanlito/nuxt-apollo-link-state-bug)

### Steps to reproduce

1. Run the app.
2. Reload the page to see issue.

### What is expected ?

Expect default state to change.

### What is actually happening?

Default state changed, then changed back to default.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c129">#c129</a>)</em></sub></div>

**Comment by dohomi** [comment]
Please update to rc-4 - this should work if not reopen again
