### ISSUE TITLE
"Network error: fetch is not defined" running example from Nuxt repository

### ISSUE THREAD

**Issue by ndarilek** [nuxt-community/apollo-module#15]
Changed into the examples/vue-apollo directory, ran:

```
npm install
npm dev
```

Visited http://localhost:3000, and received this error.

I don't know if this is the best/correct solution, but when I set up Apollo without this plugin, I had to add the isomorphic-fetch package and run:

```
import "isomorphic-fetch"
```

to define a `fetch` global. I'm not sure if doing this globally is the right way, but as of now the example isn't working, so if using isomorphic-fetch isn't correct then there should probably be modifications made to get the example working.

Thanks.

**Comment by Atinux** [comment]
Fixed with #10
