### ISSUE TITLE
ApolloProvider.provide() is deprecated. Use the 'apolloProvider' option instead...

### ISSUE THREAD

**Issue by a-zog** [nuxt-community/apollo-module#155]
### Version

[v4.0.0-rc.1](https://github.com/apollo-module/releases/tag/v4.0.0-rc.1)

### Reproduction link

[https://cmty.app/nuxt/issues/new?type=bug-report&repo=apollo-module](https://cmty.app/nuxt/issues/new?type=bug-report&repo=apollo-module)

### Steps to reproduce
Get a fresh nuxt install
Install / Config Apollo Module
Run the app

### What is expected ?

To run smoothly as it was few days ago

### What is actually happening?

Two error messages:
 apolloProvider.prefetchAll is not a function 

that is due to:

<ApolloProvider>.provide() is deprecated. Use the 'apolloProvider' option instead with the provider object directly.

### Additional comments?

Installed dependencies:

nuxtjs/apollo : 4.0.0-rc1
nuxtjs/axios : 5.3.1
nuxtjs/component-cache : 1.1.2
nuxtjs/pwa : 2.0.8
nuxt : 1.4.1

This could be possible after this vue-apollo commit: https://github.com/Akryum/vue-apollo/commit/62829e4a969532f8a4568302ff6f89286cde5b77

Some changes may be needed @ .nuxt/apollo-module.js

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c136">#c136</a>)</em></sub></div>

**Comment by DuyguKeskek** [comment]
The error is gone on my end when I remove `provide()` method. Have a look at this :
```
new Vue({
  el: '#app',
  provide: apolloProvider,
  router,
  render: h => h(App)
})
```

**Comment by dohomi** [comment]
Can you guys try this PR and see if it fixes the issue: https://github.com/nuxt-community/apollo-module/pull/158

**Comment by a-zog** [comment]
Fixed, thanks a lot for both of you

**Comment by heshamelmasry77** [comment]
@DuyguKeskek  where is this piece if code you removed ?

**Comment by silvermiguel96** [comment]
@heshamelmasry77  This is old Code
`new Vue({
  el: '#app',
  // Inject apolloProvider for components to use.
  provide: apolloProvider.provide(),
  render: h => h(App)
})`

And this is new codigo 

`new Vue({
  el: '#app',
  // Inject apolloProvider for components to use.
  apolloProvider,
  render: h => h(App)
})`
