### ISSUE TITLE
TypeError: apolloProvider.prefetchAll  in vue-apollo@3.0.0-beta.20

### ISSUE THREAD

**Issue by nodegin** [nuxt-community/apollo-module#156]
If I ran fresh npm install, `vue-apollo@3.0.0-beta.20` will be installed.

When running the application, the app will die from `TypeError: apolloProvider.prefetchAll is not a function`

However `npm i -S vue-apollo@3.0.0-beta.19` fixed this issue.

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c137">#c137</a>)</em></sub></div>

**Comment by bjunc** [comment]
Check out my issue from yesterday: https://cmty.app/nuxt/apollo-module/issues/c134

A quick fix is to use `resolutions` in your package.json file to explicitly reference beta.16 (non-breaking) until a new version of this module is released.

@dohomi my suggestion would be to nix the `^` since vue-apollo is technically in beta and breaking changes are excusable.

**Comment by dohomi** [comment]
@bjunc @nodegin could you guys verify if the https://github.com/nuxt-community/apollo-module/pull/158 is fixing your issue?

**Comment by Nainterceptor** [comment]
Hello,

`npm i nuxt-community/apollo-module#vue-apollo-upgrade-beta-21`
Seems to fix my error "apolloProvider.prefetchAll is not a function".

Thanks, I'll stick on this branch until this module release a new version, thanks

**Comment by nodegin** [comment]
@dohomi I got it working now with `npm i nuxt-community/apollo-module#vue-apollo-upgrade-beta-21` and `vue-apollo@3.0.0-beta.20`

However another error thrown on console:

`TypeError: Cannot read property '$ssrContext' of undefined`

In addition I am facing another issue now, in stable release (`^4.0.0-rc1` and `vue-apollo@3.0.0-beta.19`), the onLogin token expire is not able to use, the cookie will always expire in past, but with latest update things looks normal except the console error message... Wishing the new update will come out soon

**Comment by nodegin** [comment]
`vue-apollo` released beta.22 fixes this bug.

**Comment by ishitatsuyuki** [comment]
Not fixed at all. Please reopen.

**Comment by dohomi** [comment]
@ishitatsuyuki I just updated the dependency in #158 can you check if this resolves your issue?

**Comment by PierrickP** [comment]
@dohomi working for me. Thanks

**Comment by Atinux** [comment]
I think you can update it and publish a new version @dohomi :)

**Comment by ApricumMedia** [comment]
Unfortunately, it seems `"vue-apollo": "3.0.0-beta.25"` has reintroduced the issue. I pinned the version by `resolutions` to fix the class-component issue (2 days ago, wasn't it?).

**Comment by dohomi** [comment]
@ApricumMedia see my comments in https://github.com/nuxt-community/apollo-module/pull/158
I'm not sure which version is suitable - I run the `apollo-module rc1` and `vue-apollo beta.19` at the moment

**Comment by AndrewBogdanovTSS** [comment]
@dohomi why are you using ^ caret inside the versioning? Maybe it would be a better idea to remove that caret so all people that use your package could at least be sure that it won't break by itself by upgrading to newer versions of vue-apollo versions you don't support? 
What I suggest is switch 
`"vue-apollo": "^3.0.0-beta.19"`
to
`"vue-apollo": "3.0.0-beta.19",`

**Comment by dohomi** [comment]
@AndrewBogdanovTSS the reason is first that there hasn't been any breaking change for the past 10 months while working with `vue-apollo`. I thought 3 days ago I could ship rc2 with the most current changes - now everything seems to be delayed with fixes. But yeah... you are right I'll release rc2 temporarily with beta.19 later the evening

**Comment by ApricumMedia** [comment]
@dohomi Despite all the nagging, your work on the module is still highly appreciated, Dominic — just wanted to leave you a thanks for that.

**Comment by dohomi** [comment]
did I mention that rc2 is out? Hopefully rc3 will follow over the weekend.. I know that the naming convention is a bit off because this module relies on `vue-apollo` which by itself declares in beta. But for sure there will be stable releases coming up soon with less breaking changes and fiddling around

**Comment by AndrewBogdanovTSS** [comment]
@dohomi any news about RC3 ?

**Comment by dohomi** [comment]
rc3 is just published. It has still some issues with Nuxt v2, check out the newest issues. But for Nuxt 1.4.x everything is now updated to most recent versions of vue-apollo and the cli client

**Comment by nodegin** [comment]
@dohomi Still seeing some strange errors in console in rc3

**Comment by dohomi** [comment]
@nodegin which errors do you face?

**Comment by nodegin** [comment]
@dohomi depends on which nuxt page, I have used `head`, `asyncData` methods

**Comment by blocka** [comment]
What's the status with nuxt 2 support? I can't use resolutions since I'm using npm, not yarn, and just about every version I tried is installing beta.28 of vue-apollo, which seems to have this problem. Even if I manually install a different version of vue-apollo
