### ISSUE TITLE
"Uncaught ReferenceError: require is not defined" when using nuxt-edge

### ISSUE THREAD

**Issue by Vlaoff** [nuxt-community/apollo-module#159]
### Version

[v4.0.0-rc.2](https://github.com/apollo-module/releases/tag/v4.0.0-rc.2)

### Reproduction link

[https://github.com/Vlaoff/apollonuxt](https://github.com/Vlaoff/apollonuxt)

### Steps to reproduce

I get the error when I launch nuxt and open it in the browser

### What is expected ?

Babel should transpile the require

### What is actually happening?

Babel keeps the require

### Additional comments?

I think it's a problem with the babel 7/wepack 4 configuration.

It does not occur on nuxt 1.4.2, only on the nuxt-edge 2.0.0-xxx 

I don't know if the problem is from @nuxtjs/apollo or nuxt.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c139">#c139</a>)</em></sub></div>

**Comment by Nainterceptor** [comment]
Same error here, but, as explained in referenced issue, `npm i graphql` to put version 14.0.2 seems to be a working work around.

**Comment by aldarund** [comment]
@Vlaoff That should be fixed, could you try? ( delete lock file and reinstall)

**Comment by aldarund** [comment]
Now its only fixed for vue-cli-plugin-apollo 0.17 while here its set as 0.16
https://github.com/nuxt-community/apollo-module/blob/master/package.json#L31
So a bump of vue-cli-plugin-apollo required
@dohomi

**Comment by rwuttke** [comment]
And I think the same with graphql-tag, this uses graphql ^0.13.0, and upgrading to vue-cli-plugin-apollo uses graphql ^14.0.2.

So it looks like we need to wait for this one as well.

https://github.com/apollographql/graphql-tag/issues/208

**Comment by dohomi** [comment]
should be fixed with rc3
