### ISSUE TITLE
start() finished() loading animation sync with apollo query result

### ISSUE THREAD

**Issue by dohomi** [nuxt-community/apollo-module#16]
It would be great if this module could hook the apollo query to the `start(), finished()` function of the global loading component. 
```javascript
 apollo:{
   query:`someQuery`,
   watchLoading(isLoading){
      // => it would be great if the isLoading variable could be synchronized with the nuxt state change behaviour
          // following is not working:
          if (isLoading) {
            this.$root.$loading.start()
          } else {
            this.$root.$loading.finish()
          }
   } 
 }
}
```

**Comment by Atinux** [comment]
Hi @dohomi 

Does this code works when you implemented it?

**Comment by dohomi** [comment]
@Atinux no it does not work. The problem is, that the routing already calls start() and finish() before the `watchLoading` hook is being called. And somehow (I don't know the reason) the call of 
```
 watchLoading(isLoading){
      // => it would be great if the isLoading variable could be synchronized with the nuxt state change behaviour
          // following is not working:
          if (isLoading) {
            this.$root.$loading.start()
          } else {
            this.$root.$loading.finish()
          }
   } 
```
Is not doing any thing at all.

**Comment by Atinux** [comment]
I see @dohomi 

Why not disabling `loading` into your nuxt.js app and use a custom loader that you can start/end with events instead?

BTW, you are contributing well on this module and honestly, I don't use apollo, do you want to be a maintainer of this module?

Please mention me, I have too many Github notifications so it's hard to keep track of them :/

**Comment by dohomi** [comment]
@Atinux sure you can add me as maintainer, I will try my best.

I'm using a global indicator now and it works quite good so far. Will close it for now, maybe if I find a smarter solution I'll re-post it here

**Comment by Atinux** [comment]
@dohomi Welcome to Nuxt Community :D

**Comment by dohomi** [comment]
@Atinux OK thanks!

**Comment by IgorSzymanski** [comment]
Is there any out-of-the-box solution yet or is a custom implementation the only solution?

**Comment by arteagabriel** [comment]
@IgorSzymanski Not sure if you got it figured out but I was able to get it working with this
```
watchLoading: function(isLoading) {
    this.$nextTick(() => {
        isLoading ? this.$nuxt.$loading.start() : this.$nuxt.$loading.finish();
    })
}
```
