### ISSUE TITLE
Handling Errors when using asyncData

### ISSUE THREAD

**Issue by kavalcante** [nuxt-community/apollo-module#160]
### Version

[v4.0.0-rc.2](https://github.com/apollo-module/releases/tag/v4.0.0-rc.2)

### Reproduction link

[http://cant-reproduce-because-its-to-complicate-to-simulate-a-specific-error.com](http://cant-reproduce-because-its-to-complicate-to-simulate-a-specific-error.com)

### Steps to reproduce

Sometimes Apollo send errors reports with data included. For example, ACL errors (calling that some fields you can't view). However, the data was found and in some cases they are a real data (even with errors).

However, when calling the query in asyncData, it's break the Nuxt build, same happen with try/catch.

### What is expected ?

Errors come together on the request result and not break nuxt compilation because a "Internal server error".

### What is actually happening?

Nuxt breaks compilation and if the await is inside a try/catch, the rest of the try is ignore and the errors go right to catch function.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c141">#c141</a>)</em></sub></div>

**Comment by dohomi** [comment]
@kavalcante I don't think that I have any solution for your issue. I'd suggest to isolate your queries into multiple try catch blocks - I think this is even recommend in your case

**Comment by kavalcante** [comment]
@dohomi The problem with isolating in multiple try/catch blocks it's that when you catch the problem, only returns the error, not included the data.

Maybe the only solution as far I know, is not using SSR in this specific page. Because with the common apollo call, it's work. Because all errors are sended to `error` callback.

Thanks for the support @dohomi
