### ISSUE TITLE
window.__NUXT__.apollo is undefined

### ISSUE THREAD

**Issue by ndarilek** [nuxt-community/apollo-module#17]
Getting this error attempting to use this module on an app built with `nuxt generate`. No initial state is available.

With this line:
```
        initialState: window.__NUXT__.apollo.<%= key === 'default' ? 'defaultClient' : key %>,
```
What happens when no initial state is available? How would I tell my client that I don't have an initial state payload for it?

**Comment by Atinux** [comment]
Actually should always have a state, I generated a website with it and it works fine
