### ISSUE TITLE
Nuxt apollo module crashes ava

### ISSUE THREAD

**Issue by ImreC** [nuxt-community/apollo-module#171]
### Version

[4.0.0-rc2.3](https://github.com/apollo-module/releases/tag/4.0.0-rc2.3)

### Reproduction link

[https://github.com/ImreC/nuxt-ava-problem](https://github.com/ImreC/nuxt-ava-problem)

### Steps to reproduce

- npm run test  -->  Ava crashes with 'nuxt build error'
- remove store/index.js line 1 (the gql import)  --> Ava works fine 
- npm run dev always works and produces results as expected

### What is expected ?

I am trying to run ava tests on a default app containing the apollo module. I am expecting ava testing using npm run test to work

### What is actually happening?

Ava testing crashes with a 'nuxt build error'. Removing the gql import fixes everything. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c149">#c149</a>)</em></sub></div>

**Comment by dohomi** [comment]
Seems to be a misconfiguration of AVA? Or is anything missing on this package?

**Comment by kieusonlam** [comment]
I’m closing this issue because it has been inactive for a few months.
