### ISSUE TITLE
set custom headers

### ISSUE THREAD

**Issue by gomezmark** [nuxt-community/apollo-module#176]
<ApolloProvider>.provide() is deprecated. Use the 'apolloProvider' option instead with the provider object directly.
× error TypeError: apolloProvider.prefetchAll is not a function

I

**Comment by ryanhmaas** [comment]
If you want custom headers, something like this will work:

nuxt.config.js

```
apollo: {
    clientConfigs: {
      default: '~/apollo/client-configs/default.js'
    }
  }
```

apollo/client-configs/default.js

```
export default function(context){
    return {
        httpEndpoint: 'yourURLHere',
        httpLinkOptions: {
            headers:{
                'X-Custom-Header': 'value'
            }
        }
    }
}
```

I have it working with Shopify's API which requires a custom header.

**Comment by dailycommit** [comment]
Is it possible to add a dynamic header ?
I am having trouble with Hasura, I need to determine some user roles for access control and these roles need to be added to the header like
``x-hasura-role : "user" `` or ``x-hasura-role: "admin"``  etc.
according to the logged in user can be dozens of roles so I have to change them dynamically.

**Comment by mfdeux** [comment]
@dailycommit Did you find the solution? You can add request-specific context, for example:

```javascript
apolloClient.query({
    query: GRAPHQL_QUERY,
    variables: {
        var1: "this is a variable"
    },
    context: {
        headers: {
            X-Hasura-Role: "public"
        }
    }
})
```

**Comment by dailycommit** [comment]
hey @mfdeux, yes I found how to do it, thank you 😊👨‍💻

**Comment by Youhan** [comment]
Just found out you could also do this if you want to dynamically change the endpoint:
```
apolloClient.query({
    query: GRAPHQL_QUERY,
    variables: {
        var1: "this is a variable"
    },
    context: {
        uri: "https://YOUR_CUSTOM_ENDPOINT",
    }
})
```

**Comment by lroy83** [comment]
@dailycommit @Youhan do you know how to use dynamic header with subscriptions?

**Comment by dmitrijt9** [comment]
Why it's not possible to pass custom variables in smart queries? 

At least it's not in documentation https://github.com/vuejs/vue-apollo/blob/master/docs/api/smart-query.md

**Comment by dmitrijt9** [comment]
> Why it's not possible to pass custom variables in smart queries?
> 
> At least it's not in documentation https://github.com/vuejs/vue-apollo/blob/master/docs/api/smart-query.md

Ok. I'm taking this back. You can add custom headers in same way like @mfdeux mentioned above even if it's not in docs. 

Just keep in mind, that if you want to use for example a vuex store for setting the header then the context must be a function so that you can reference `this`. 

Example:
```
context() {
    return {
        headers: {
            'X-Examlpe-Header': this.$store.state.example.data
        }
    }
}
```
