### ISSUE TITLE
THIS IS A SECURY ISSUE! - flatmap-stream@0.1.1

### ISSUE THREAD

**Issue by appinteractive** [nuxt-community/apollo-module#181]
##THIS IS A SECURY ISSUE!

### Version

[v4.0.0-rc.3](https://github.com/apollo-module/releases/tag/v4.0.0-rc.3)

### Reproduction link

[https://github.com/dominictarr/event-stream/issues/116](https://github.com/dominictarr/event-stream/issues/116)
https://www.npmjs.com/advisories/737

### Steps to reproduce

Run `yarn audit` in a project that has `@nuxtjs/apollo` as a dependency.

![Bildschirmfoto 2018-11-27 um 11.38.55.png](https://cmty.s3.eu-west-1.amazonaws.com/98543958/b6a63ce0-f230-11e8-b304-ad599efdefc2.png)

### What is expected ?

flatmap-stream > 0.1.1

### What is actually happening?

flatmap-stream = 0.1.1

##THIS IS A SECURY ISSUE!
https://github.com/dominictarr/event-stream/issues/116
https://www.npmjs.com/advisories/737

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c161">#c161</a>)</em></sub></div>

**Comment by appinteractive** [comment]
I think you have to re-publish the package on npm after the build. Seems that the issue does not exists when checking out the repo and installing. Will try to remove my node_modules in my project and install again...

**Comment by appinteractive** [comment]
Update: If you have that issue, remove the whole node_modules and your yarn.lock or package-lock.json and run the install again. After that you should be save. 

My advice would still be a bump in version so that would not be neccessary anymore.

**Comment by manniL** [comment]
![image](https://user-images.githubusercontent.com/640208/49085347-bc456900-f249-11e8-9794-338abb97a092.png)

It's the vue-cli plugin that is affected, not that lib.

However, I've updated the deps on the branch 👍
