### ISSUE TITLE
Error apolloProvider.provide is not a function

### ISSUE THREAD

**Issue by bagahunda** [nuxt-community/apollo-module#188]
### Version

[v4.0.0-rc.3](https://github.com/apollo-module/releases/tag/v4.0.0-rc.3)

### Reproduction link

[https://github.com/bagahunda/codeguru-adonis-graphql-front](https://github.com/bagahunda/codeguru-adonis-graphql-front)

### Steps to reproduce

just install the @nuxtjs/apollo and run `npm run dev`

### What is expected ?

App runs smoothly

### What is actually happening?

app crashes

### Additional comments?

Got an error apolloProvider.provide is not a function on app start.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c165">#c165</a>)</em></sub></div>

**Comment by dohomi** [comment]
try out https://github.com/nuxt-community/apollo-module/releases/tag/v4.0.0-rc2.3
This version should work as expected

**Comment by heshamelmasry77** [comment]
not working @dohomi

**Comment by dohomi** [comment]
Without a repo I'm not able to help.

**Comment by dohomi** [comment]
Update to rc-4 - this should fix the issue. If not re-open again
