### ISSUE TITLE
Api Key for Apollo Engine

### ISSUE THREAD

**Issue by ardian-c** [nuxt-community/apollo-module#192]
Hi all, 

I am trying to integrate Apollo Engine with Nuxt and I need to add the API key, but I don't know how can I do that. I see that in nuxt.config it is a part for Apollo Engine, however, I don't know where I should specify the Apollo Engine API key. 

Thanks

**Comment by ManUtopiK** [comment]
I don't see what you mind by API key? You have to configure your endpoint in your nuxt.config.js like so:
```
apollo: {
    clientConfigs: {
      default: {
        httpEndpoint: 'http://localhost:3000/graphql/'
      }
    }
  }
```
This is for development only. Read more here: https://github.com/nuxt-community/apollo-module

**Comment by ardian-c** [comment]
Yes, I have that working, the issue I have is with [Apollo Engine](https://www.apollographql.com/docs/references/engine-proxy) API key. I don't know where to add that information.

**Comment by tha80** [comment]
@ardian-c:

As far as I know you cannot use Apollo Engine from within apollo-client (and all projects that use apollo-client under the hood like vue-apollo or nuxt-apollo).

Apollo Engine is used within apollo-server (so the server side of your GraphQL stack). All metrics gets transmitted by the server to Apollo Engine.

**Comment by ardian-c** [comment]
@tha80, I see, so in my server (Elixir/Absinthe) I'll need to add something like this [package](https://github.com/sikanhe/apollo-tracing-elixir), to allow tracing. Thanks!
