### ISSUE TITLE
defaultClientConfig is not a function when using absinthe socket

### ISSUE THREAD

**Issue by lrosa007** [nuxt-community/apollo-module#194]
### Version

[v4.0.0-rc.2](https://github.com/apollo-module/releases/tag/v4.0.0-rc.2)

### Reproduction link

[https://github.com/lrosa007/apollo-module-example](https://github.com/lrosa007/apollo-module-example)

### Steps to reproduce

1. clone the repo
2. enter the folder
3. yarn dev or npm run dev
4. try to load the root page in a browser

### What is expected ?

default nuxt landing page loads normally

### What is actually happening?

Displays an error claiming defaultClientConfig is not a function.

References code generated by line 39-43 in `/lib/templates/plugin.js`

When I comment out the absinthe socket stuff, it runs just fine. So I've been trying to figure what about that code is messing up how my plugin gets imported within nuxt.

I threw in some console logs in the generated `.nuxt/apollo-module.js` file and saw that the `require('~/plugins/apollo.js')` is returning something odd.

### Additional comments?

I'll probably also make an issue in the repo for [absinthe](https://github.com/absinthe-graphql/absinthe-socket)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c174">#c174</a>)</em></sub></div>

**Comment by dohomi** [comment]
Please update to rc-4 - this should work if not reopen again

**Comment by lrosa007** [comment]
I'll give it a go later today, thanks
