### ISSUE TITLE
apollo client doesn't update when store update

### ISSUE THREAD

**Issue by yaki4** [nuxt-community/apollo-module#196]
### Version

[v4.0.0-rc.3](https://github.com/apollo-module/releases/tag/v4.0.0-rc.3)

### Reproduction link

[https://grapheader-nmsrtiwlue.now.sh/](https://grapheader-nmsrtiwlue.now.sh/)

### Steps to reproduce

Increment value in store with one of the two buttons. 
The first one will refetch the first query and the second one will execute the second query.

### What is expected ?

Apollo client use updated store value.

### What is actually happening?

Apollo client use old store value.
I have to reload my window to use the new client.

### Additional comments?

The first time i had this bug was with i18n, my headers was not set correctly with the new lang.
You can find a repo here https://gitlab.com/yaki4/grapheader.git

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c176">#c176</a>)</em></sub></div>

**Comment by dohomi** [comment]
Please update to rc-4 - this should work if not reopen again
