### ISSUE TITLE
client-server hydration error on current master branch

### ISSUE THREAD

**Issue by dohomi** [nuxt-community/apollo-module#198]
@kieusonlam @kevinmarrec could you guys try the current master branch? I merged the potential update but now the SSR client/server hydration breaks. 
There must be some missing pieces. If you check out this repo and run dev,dev2,dev3 and open the console you will find the hydration error.
@Akryum could you maybe have a look what is missing with the most recent Vue 2.6.6 and vue-apollo as dependencies? Thanks!

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c178">#c178</a>)</em></sub></div>

**Comment by kieusonlam** [comment]
@dohomi  I think it should be the vue dependencies problem.

`vue-apollo v3.0.0-beta.28` using `serverPrefetch` which is only existed in `vue 2.6+`

Do you have any public graphql api use to test this? I will give it a try.

Or you try it yourself Install `vue@2.6.6` `vue-template-compiler@2.6.6` `vue-server-renderer@2.6.6` and see how it goes.

**Comment by dohomi** [comment]
@kieusonlam just check out the code and run the npm scripts.. I just checked and I had vue 2.6.6 inside of my project and it still didn't work. https://github.com/nuxt-community/apollo-module/blob/master/package.json#L57

I thought the most recent Nuxt does require the newest vue as well. I have 3 test project inside this repo you can fire them up in your local environment

**Comment by kieusonlam** [comment]
@dohomi Did you try to remove package-lock.json, or. yarn.lock and reinstall deps?

It seem to work for me. I tried it on one of my projects and codesandbox too. 

Here is codesanbox. I did update a bit graphql query in `dev` folder
https://codesandbox.io/s/1k4k1lloq
you can run `yarn dev` in the terminal and see if it work.

another example: https://codesandbox.io/s/mz60xk9048

**Comment by dohomi** [comment]
@kieusonlam this is very strange. Did you clone this repo and ran dev,dev2 or dev3 locally? You just need to add .env and your API endpoints. The current master of this project has newest vue and vue-server-rendered as you can see in package-lock.json. And still all fixtures are failing with client server hydration error.

**Comment by kieusonlam** [comment]
@dohomi Here is my screenshot.

![image](https://user-images.githubusercontent.com/13093313/52828553-d16cbe00-30fb-11e9-89ec-989f9d5efd57.png)

Could it be the dev environment?

**Comment by dohomi** [comment]
You are totally right.. I had some sw.js bugging into the localhost:3000 port from a different environmet.. everything good I'll tag this version now
