### ISSUE TITLE
Page infinite loading if contains apollo query

### ISSUE THREAD

**Issue by yaki4** [nuxt-community/apollo-module#199]
### Version

[v4.0.0-rc.4](https://github.com/apollo-module/releases/tag/v4.0.0-rc.4)

### Reproduction link

[https://graphnewreader-uqpacjfhny.now.sh](https://graphnewreader-uqpacjfhny.now.sh)

### Steps to reproduce

Click one of the link. 
The page load with data. 
Reload the page.

link for git: https://gitlab.com/yaki4/grapheader.git

### What is expected ?

Page load and display data.

### What is actually happening?

The second and third page with apollo query load forever.

### Additional comments?

You can fin in package.json the requirement for vue, vue-template-compiler and vue-server-renderer.
I try remove and rebuilt yarn.lock without success

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c181">#c181</a>)</em></sub></div>

**Comment by kieusonlam** [comment]
I think there is something with the `skip` function. Remove it will solve the problem 

Same as https://github.com/nuxt-community/apollo-module/issues/200

Also note that `vue-apollo v3.0.0-beta.28` with the `prefetch` option default is `true` so set it to `false` if you don't want to prefetch data.

**Comment by yaki4** [comment]
Oh you right if i remove the skip function the page will load correctly.
However the other issue show another problem. The fact that if i use a store value in my client, it'll not update properly.

**Comment by drewgarratt** [comment]
I've had similar issues with the upgrade to the new RC.
SSR seems to hang infinitely even when skip option is removed.
Tricky to look at just where it seems to be failing.

**Comment by dohomi** [comment]
I'd highly recommend to delete package-lock/yarn.lock remove the whole node_modules folder and run the install again. Seems to me that some version conflict exists

**Comment by drewgarratt** [comment]
@dohomi I'm afraid this had no effect and the development still stalls

**Comment by dhritzkiv** [comment]
I am also experiencing this issue when setting the `skip` field in a query in SSR. It doesn't matter if `skip` is a literal boolean, or a method that returns a reactive value.

I was able to get around it in some cases by setting `prefetch: false` on the query, but that's not an ideal workaround.

**Comment by dhritzkiv** [comment]
This looks to be a bug in vue-apollo. Here's a PR that purportedly fixes it: https://github.com/Akryum/vue-apollo/pull/511

**Comment by kieusonlam** [comment]
Merged https://github.com/nuxt-community/apollo-module/pull/211
