### ISSUE TITLE
CORS: the content must be served over HTTPS.

### ISSUE THREAD

**Issue by iliyaZelenko** [nuxt-community/apollo-module#204]
[link](https://nuxtjs.cmty.io/issues/new) to create questions does not work

> Mixed Content: The page at 'https://ilya-blog.herokuapp.com/' was loaded over HTTPS, but requested an insecure resource 'http://ilya-blog-backend.herokuapp.com/graphql'. This request has been blocked; the content must be served over HTTPS.

I know to fix the error I need to replace "http" with "https", but the problem is that this does not help.

I googled the entire Internet and really do not know what the reason.

Error start appears when I moved the site to the heroku.

I am 100% sure that it is used "https". Tell me something, or else I'm stumped.

**Comment by iliyaZelenko** [comment]
I have long solved this error. The reason was very strange, it was necessary to replace `https://ilya-blog-backend.herokuapp.com/graphql/` with `https://ilya-blog-backend.herokuapp.com/graphql`.  😄 🔫 ... 💀

**Comment by Jones-S** [comment]
Do you have any other recommendations. In my case I don't have any slash problem, but still I would get a CORS error...
could you maybe share your apollo client config?

**Comment by iliyaZelenko** [comment]
@Jones-S my [project and config](https://github.com/iliyaZelenko/blog-frontend/blob/master/src/configs/apollo.ts).

**Comment by Jones-S** [comment]
@iliyaZelenko thank you by the way. Back then I was in deep shit with a deadline. :)
Anyway, your answer was very much appreciated.
I finally found out that I messed up other things with CORS (my backend server sent two headers with different CORS allowed origins... 🙈), so I had to fix that...
