### ISSUE TITLE
Prefetch in Components in NUXTJS

### ISSUE THREAD

**Issue by razorabhu1995** [nuxt-community/apollo-module#209]
Prefetch in apollo queries works in pages i.e. routes in NuxtJS but doesnot work in Components!!
Is there solution for this???

I am using Nuxt version1.0.0
@dohomi

**Comment by dohomi** [comment]
@razorabhu1995 you have to upgrade to the most recent version of Nuxt and Vue

**Comment by razorabhu1995** [comment]
@dohomi do you how to upgrade Nuxt Safely from Nuxt1.0.0 to latest

coz when i upgrade there is version mismatch with  Vue!!

Can you suggest the safest way??

**Comment by razorabhu1995** [comment]
@dohomi do you how to upgrade Nuxt Safely from Nuxt1.0.0 to latest

coz when i upgrade there is version mismatch with  Vue!!

Can you suggest the safest way??

**Comment by dohomi** [comment]
You have to read the changelog of Nuxt and see what has changed compared to your project files

**Comment by razorabhu1995** [comment]
Thanks i upgraded it and it worked!!

But new problem is that prefetch only works when user is logged in!!
prefetch doesnot work in logged out data!!

Any idea what happened there?? @dohomi
