### ISSUE TITLE
Implicit dependency on `webpack-node-externals`

### ISSUE THREAD

**Issue by pi0** [nuxt-community/apollo-module#212]
### Version

[v4.0.0-rc.4](https://github.com/apollo-module/releases/tag/v4.0.0-rc.4)

### Reproduction link

[https://github.com/nuxt/now-builder/issues/31](https://github.com/nuxt/now-builder/issues/31)

### Steps to reproduce

-

### What is expected ?

-

### What is actually happening?

now-builder uses a non-development distribution of `nuxt`, thus it does not need and does not installs `webpack-node-externals`. 

### Additional comments?

It can be advised to use `apollo-module` in `devModules: []` (Because it is only needed for build/dev time to inject templates) or we add `webpack-node-externals` dependency to this package.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c194">#c194</a>)</em></sub></div>

**Comment by kieusonlam** [comment]
Merged https://github.com/nuxt-community/apollo-module/pull/189
