### ISSUE TITLE
Customizing global errorHandler fatal crashes server

### ISSUE THREAD

**Issue by drewbaker** [nuxt-community/apollo-module#213]
### Version

[v4.0.0-rc.4](https://github.com/apollo-module/releases/tag/v4.0.0-rc.4)

### Reproduction link

[https://codepen.io/drewbaker/pen/gJMvoO](https://codepen.io/drewbaker/pen/gJMvoO)

### Steps to reproduce

1) In  `nuxt.config.js` just define the example `errorHandler` as shown in the docs. It's enough to just do a simple `console.log(error)` too.
2) Make a GQL request, requesting something that doesn't exists (like `links` instead of `link`) and the server will crash.
3) The server will crash with a bog error (see screenshots).
4) If you do not define the `errorHandler` (delete it from `nuxt.config.js`), it will log errors to console and not crash.

### What is expected ?

Log errors to console and not crash.

### What is actually happening?

Big error in console, not seemingly related to GQL or Apollo, and server crashes.
![Screen Shot 2019-05-11 at 11.44.28 PM.png](https://cmty.s3.eu-west-1.amazonaws.com/98543958/80dbb150-7483-11e9-8f52-c377783d261d.png)

### Additional comments?

The same query in GraphiQL produces a nice error. See screenshot.
![Screen Shot 2019-05-11 at 11.47.12 PM.png](https://cmty.s3.eu-west-1.amazonaws.com/98543958/9a32a960-7483-11e9-8f52-c377783d261d.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c197">#c197</a>)</em></sub></div>

**Comment by kieusonlam** [comment]
Can you create a minimal repo or codesanbox for this?

**Comment by drewbaker** [comment]
Yes will do tomorrow!

**Comment by kieusonlam** [comment]
I did some change on errorHandler, it's should be fixed. Checkout the newer version.
