### ISSUE TITLE
TypeError Cannot read property 'freezeResults' of null

### ISSUE THREAD

**Issue by mdskinner** [nuxt-community/apollo-module#222]
### Version

[v4.0.0-rc.5](https://github.com/apollo-module/releases/tag/v4.0.0-rc.5)

### Reproduction link

[https://codesandbox.io/s/codesandboxnuxt-kdgpg?fontsize=14](https://codesandbox.io/s/codesandboxnuxt-kdgpg?fontsize=14)

### Steps to reproduce

clean install - implement @nuxtjs/apollo as described
![Screenshot 2019-05-22 at 12.00.37 PM.png](https://cmty.s3.eu-west-1.amazonaws.com/98543958/74e7c670-7c2d-11e9-8527-3d2edcbdd45a.png)

### What is expected ?

apollo to be implemented

### What is actually happening?

TypeError
Cannot read property 'freezeResults' of null

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c202">#c202</a>)</em></sub></div>

**Comment by kieusonlam** [comment]
For now, I'm not pretty sure what happen. `freezeResults` in `apollo-cache-inmemory` supposed to set to false by default.

The current solution, you can manual set `freezeResults` like this.
```js
   apollo: {
    clientConfigs: {
      default: {
        httpEndpoint:
          "https://api.graph.cool/simple/v1/cj1dqiyvqqnmj0113yuqamkuu",
        inMemoryCacheOptions: {
          freezeResults: false
        }
      }
    }
  }
```

**Comment by kieusonlam** [comment]
Fixed on new release version.
