### ISSUE TITLE
default.httpEndpoint parameter not working with non-http link

### ISSUE THREAD

**Issue by zachheine** [nuxt-community/apollo-module#228]
### Version

[v4.0.0-rc.6](https://github.com/apollo-module/releases/tag/v4.0.0-rc.6)

### Reproduction link

[https://jsfiddle.net/28xvoum1/2/](https://jsfiddle.net/28xvoum1/2/)

### Steps to reproduce

I am using netlify functions to run the GraphQL server and normally make requests to `/.netlify/functions/graphql` so that it works locally and when deployed.  However, the default.httpEndpoint parameter is not working with this link.

### What is expected ?

I use the link that I use in normally http requests and it works.

### What is actually happening?

Requires http:// prefix.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c205">#c205</a>)</em></sub></div>

**Comment by negezor** [comment]
In most cases, this is not an error, as the server needs to know where to send requests.

**Comment by zachheine** [comment]
I use nuxt proxy:

```
// @nuxtjs/proxy configuration
proxy: {
  '/.netlify': {
    target: 'http://localhost:9000',
    pathRewrite: { '^/.netlify/functions': '' }
  }
}
```

and it works for:

```
this.$axios.$get('/.netlify/functions/user)
```

**Comment by zachheine** [comment]
` Error: [Apollo module] Client configuration "default" must define httpEndpoint or link option.`

Can someone explain the `link option`?  I saw the `httpEndpoint` has some restrictive Regex (was considering a Pull Request to loosen it) but maybe `link option` provides a solution?

**Comment by kieusonlam** [comment]
You can take a look at [vue-cli-plugin-apollo document](https://vue-cli-plugin-apollo.netlify.com/guide/configuration.html#createapolloclient-options) or [here](https://github.com/Akryum/vue-cli-plugin-apollo/blob/master/graphql-client/src/index.js)

link option is use for creating your own httpLink instead of the default created by `vue-cli-plugin-apollo`

nuxt.config.js
```js
{
  apollo: {
     clientConfigs: {
        default: '~/apollo/apollo-config.js'
     }
  }
}
```
~/apollo/apollo-config.js
```js
import { createHttpLink } from 'apollo-link-http'

export default (ctx) => {

  const httpLink = createHttpLink({
    uri: 'http://localhost:3020/graphql',
  })

  return {
    link,
    defaultHttpLink: false
    ...
  }
}
```
more about it create http link https://www.apollographql.com/docs/link/links/http/

**Comment by SilentDepth** [comment]
Why not just loosen the `http://` prefix regexp to accept relative uri? Vue Apollo support that anyway. Is there any consideration on this?

**Comment by kieusonlam** [comment]
After considering, I removed the regexp.
