### ISSUE TITLE
store.state is false on client refresh in v2.0 networkInterface default function

### ISSUE THREAD

**Issue by dohomi** [nuxt-community/apollo-module#23]
@Atinux thanks for merging my PR but it seems to not work properly:
```javascript
defaultNetworkInterface.js
export default ({store, req, isServer} ) => {
  let token
  if (isServer) {
    token = getTokenFromCookie(req)
    token && store.commit('SET_AUTH_TOKEN', token)
  } else {
    token = store.state.authToken
  }
  console.log(isServer, token) // => token is always empty on client side
}
```
The network interface is missing the store states on `isServer===false`.

This brings me to a general question: how is Vuex supposed to work? If users commit a Vuex store state on server side, should the Vuex state be present on client side as well? I think the plugin/module behaviour might miss to persist the correct Vuex state at the moment

**Comment by Atinux** [comment]
Hi @dohomi 

With the new release of Nuxt.js, the store replace state has been moved after plugins calls, see https://github.com/whtsky/nuxt.js/blob/add2bcb89fdaa4b366694a04b2cc95c8a11cad33/lib/app/index.js#L147

What you can do on client side is to read `window.__NUXT__.state.authToken`

**Comment by dohomi** [comment]
@Atinux Thanks works great!
