### ISSUE TITLE
Module doesn't load

### ISSUE THREAD

**Issue by lambda0xff** [nuxt-community/apollo-module#240]
### Version

[v4.0.0-rc.8.2](https://github.com/apollo-module/releases/tag/v4.0.0-rc.8.2)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-08rtv](https://codesandbox.io/s/codesandbox-nuxt-08rtv)

### Steps to reproduce

yarn add @nuxtjs/apollo 
yarn add vue-template-compiler@2.6.6 vue-server-renderer@2.6.6

add to modules section of nuxt.config.js
modules: [
...,  
'nuxtjs/apollo'
...
]

yarn dev // to launch nuxt app

### What is expected ?

workin application

### What is actually happening?

build crash:
 FATAL  Cannot convert undefined or null to object

  at Function.keys (<anonymous>)
  at ModuleContainer.module.exports (node_modules/@nuxtjs/apollo/lib/module.js:12:35)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:189:34)
  at promise.then (node_modules/@nuxt/utils/dist/utils.js:1796:43)

   ╭────────────────────────────────────────────────────╮
   │                                                    │
   │   ✖ Nuxt Fatal Error                               │
   │                                                    │
   │   TypeError: Cannot convert undefined or null to   │
   │   object                                           │
   │                                                    │
   ╰────────────────────────────────────────────────────╯

error Command failed with exit code 1.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c220">#c220</a>)</em></sub></div>

**Comment by kieusonlam** [comment]
Hi, sorry for late response, `apollo-module` require apollo config in `nuxt.config.js` to be worked. Check the README and let me know if is there any problem.

**Comment by mccxiv** [comment]
I ran into the same thing, indeed it's my fault for not reading the docs more carefully. 
Could the error be made more clear for future dummies like me?

**Comment by kieusonlam** [comment]
@mccxiv Just fixed it. https://github.com/nuxt-community/apollo-module/commit/d8622883236fe78015c09b7b8469d3f6620c4954
