### ISSUE TITLE
when onLogin after onLogout, cannot get tokens.

### ISSUE THREAD

**Issue by wan2land** [nuxt-community/apollo-module#243]
In my service, After logging out, i cannot login.

The situation is as follows:

```js
await this.$apolloHelpers.onLogin(token)
console.log(11, this.$apolloHelpers.getToken()) // print token

await this.$apolloHelpers.onLogout()
console.log(22, this.$apolloHelpers.getToken()) // print undefined

await this.$apolloHelpers.onLogin(token)
console.log(33, this.$apolloHelpers.getToken()) // expect token, but print undefined
```

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c222">#c222</a>)</em></sub></div>

**Comment by kieusonlam** [comment]
can you setup a codesanbox or a github repo for this?

**Comment by wan2land** [comment]
@kieusonlam 

https://codesandbox.io/s/codesandbox-nuxt-1dm65?fontsize=14

**Comment by mattwr18** [comment]
We are also having an issue that must be the same, or related. When we upgraded to `"@nuxtjs/apollo": "^4.0.0-rc10"`, our logout/login functionality. 
When a user logs out, they are redirected to the `login` page, but if a log in is attempted, the log in is successful, but the cookies are not set, so the user is not redirect to the root path.

If one refreshes the page, then it all works as expected. Downgrading to `rc9` solves the issue.
We had a look at the release notes and the major change is https://github.com/nuxt-community/apollo-module/pull/242, where `cookie-universal` replaces `jsCookie`.

Our repo is https://github.com/Human-Connection/Human-Connection
For now, we have just downgraded to `rc9`, but if anyone has an idea how we can debug what is going on, it would be greatly appreciated.

**Comment by kieusonlam** [comment]
fixed on v4.0.0-rc.11

**Comment by mattwr18** [comment]
hey @kieusonlam, I tested this locally, and it's fixed our bug!!
Thanks!!

**Comment by andreiscripcaru22** [comment]
> We are also having an issue that must be the same, or related. When we upgraded to `"@nuxtjs/apollo": "^4.0.0-rc10"`, our logout/login functionality broke.
> When a user logs out, they are redirected to the `login` page, but if a log in is attempted, the log in is successful, but the cookies are not set, so the user is not redirect to the root path.
> 
> If one refreshes the page, then it all works as expected. Downgrading to `rc9` solves the issue.
> We had a look at the release notes and the major change is #242, where `cookie-universal` replaces `jsCookie`.
> 
> Our repo is https://github.com/Human-Connection/Human-Connection
> For now, we have just downgraded to `rc9`, but if anyone has an idea how we can debug what is going on, it would be greatly appreciated.

For me, I've had a similar issue and it was that `universal-cookie` is storing the cookie for current path not for root, specifying this solved it for me.

**Comment by mattwr18** [comment]
Great that you pass this info on for others, the changes made from `rc10` to `rc11` fixed our issue, though I can't remember what those changes were at this time.
