### ISSUE TITLE
Option to skip resetStore when setting token with onLogin

### ISSUE THREAD

**Issue by rlgod** [nuxt-community/apollo-module#244]
### What problem does this feature solve?

For short-lived tokens, this causes any in-flight requests to be cancelled due to the resetStore() call in the onLogin function.

### What does the proposed changes look like?

Add an additional argument to skip store reset when calling onLogin and onLogout.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c223">#c223</a>)</em></sub></div>

**Comment by kieusonlam** [comment]
Added it on v4.0.0-rc.11

**Comment by jankal** [comment]
@kieusonlam the implementation of this feature is incomplete.

The TypeScript typings are missing the new parameter.
