### ISSUE TITLE
websockets authentication fails due to the use of vue-cli-plugin-apollo

### ISSUE THREAD

**Issue by dohomi** [nuxt-community/apollo-module#254]
Hi 

I just found out in a different project that vue-cli-plugin-apollo does not work with authentication:
https://github.com/Akryum/vue-cli-plugin-apollo/pull/144

So currently I wonder if anybody uses websockets at all? Because ultimately all the authorization should fail 

Maybe this plugin should wire up its own config being independent or should reference the PR patch

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c238">#c238</a>)</em></sub></div>

**Comment by kieusonlam** [comment]
The `vue-cli-plugin-apollo` just release new version.

**Comment by dohomi** [comment]
@kieusonlam thanks for keeping up so quick

**Comment by rigelk** [comment]
@dohomi have you managed to authentify with the last version? I certainly couldn't, even with the patched `vue-cli-plugin-apollo`.
