### ISSUE TITLE
Typescript issue VueApolloOptions

### ISSUE THREAD

**Issue by ScreamZ** [nuxt-community/apollo-module#255]
### Version

[v4.0.0-rc.12](https://github.com/apollo-module/releases/tag/v4.0.0-rc.12)

### Reproduction link

[https://no.fr](https://no.fr)

### Steps to reproduce

Try to compile with `nuxt-build`, see the error with tsc `/node_modules/vue-apollo/types/options"' has no exported member 'VueApolloOptions'.`

### What is expected ?

This should be correctly typed or ignored…

### What is actually happening?

This is not

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c239">#c239</a>)</em></sub></div>

**Comment by kieusonlam** [comment]
I updated `vue-apollo` to newer version, there are some breaking change on typescript. Did you rebuild your yarn.lock or package-lock.json, I think it's some mismatch `vue-apollo` version.
