### ISSUE TITLE
Implement file upload support

### ISSUE THREAD

**Issue by lewebsimple** [nuxt-community/apollo-module#259]
### What problem does this feature solve?

Right now, file uploads using the GraphQL multipart request specification are not possible with nuxt-apollo.

Adding support for [apollo-upload-client](https://github.com/jaydenseric/apollo-upload-client) shouldn't be too hard to implement.

### What does the proposed changes look like?

If I understand correctly, the upload link simply replaces the HTTP link inside the client config.
From the end-user's perspective, this [tutorial](https://scotch.io/tutorials/handling-file-uploads-in-graphql-and-vue) should give an idea of how things work on the frontend.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c244">#c244</a>)</em></sub></div>

**Comment by kieusonlam** [comment]
Hi @lewebsimple 

`apollo-upload-client` is already implemented in `vue-cli-plugin-apollo` https://github.com/Akryum/vue-cli-plugin-apollo/blob/a2e8560807f26af9dcb0fbe1958e0eb47696f7b8/graphql-client/src/index.js#L3

I have a project with file upload and it is working

![image](https://user-images.githubusercontent.com/13093313/65615570-c4924000-dfe3-11e9-9d5b-36049e357fe2.png)

maybe something wrong with your backend?

**Comment by lewebsimple** [comment]
Huh! Didn't notice vue-apollo was using apollo-upload-client by default.
Closing the issue, thanks!
