### ISSUE TITLE
Can use apollo in vuex ?

### ISSUE THREAD

**Issue by lyquocnam** [nuxt-community/apollo-module#26]
Can use apollo in vuex ?

**Comment by dohomi** [comment]
you can always dispatch to Vuex inside of the `result` hook of vue-apollo

**Comment by lyquocnam** [comment]
@dohomi can you tell me more detail, please

**Comment by dohomi** [comment]
check out the docs of vue-apollo: https://github.com/Akryum/vue-apollo#advanced-options
there you will find an example about the 
```
result({data}){
  this.$store.dispatch('YOUR_STORE',data.yourQuery)
}
```
