### ISSUE TITLE
Don't require default client to be defined

### ISSUE THREAD

**Issue by rchl** [nuxt-community/apollo-module#263]
### What problem does this feature solve?

It makes it possible to use the module without having default client defined.

This should be possible now that vue-apollo removed need for it in https://github.com/Akryum/vue-apollo/issues/548

### What does the proposed changes look like?

Remove this check:
https://github.com/nuxt-community/apollo-module/blob/c9756814c49e0dae7ed4ce450af740bb791dd824/lib/module.js#L16

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c246">#c246</a>)</em></sub></div>

**Comment by kieusonlam** [comment]
I'll take a look at this

**Comment by chriscalo** [comment]
If a default client config is not provided, what will be the default client values?
