### ISSUE TITLE
Local state documentation

### ISSUE THREAD

**Issue by colinmeinke** [nuxt-community/apollo-module#266]
### What problem does this feature solve?

Give an example of how to create and use a client to store local state in a Nuxt app. I spent a bunch of time trying to work this out without success, and found the documentation unhelpful.

### What does the proposed changes look like?

Additions to the readme.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c248">#c248</a>)</em></sub></div>

**Comment by kieusonlam** [comment]
I just add a local state demo, you can check out if it is the right one
https://github.com/nuxt-community/apollo-module/tree/master/test/fixture-local-state

Based on `vue-cli-plugin-apollo` document: https://vue-cli-plugin-apollo.netlify.com/guide/client-state.html

**Comment by colinmeinke** [comment]
@kieusonlam sorry for the slow response, thanks for this! It works great!
