### ISSUE TITLE
I don't understand apollo-module SSR behavior

### ISSUE THREAD

**Issue by nyl-auster** [nuxt-community/apollo-module#27]
Hello there !

When you go here AND then click on "blog" page (the first time ) https://yineo-website-rnuhrxdiwf.now.sh/contact 
What i get : 

1. Loading bar at the top go to 100% loaded, but posts are not yet loaded
2. My blogs posts are displaying "loading" 
3. Blog posts appears once pulled by apollo from my GraphQL API server

What i expected : 
- Blog posts already rendered as html string by nodejs server
- OR : loading bar do not go up until 100% if posts are not yet loaded

Am i doing something wrong here ?
Are posts actually Server Side rendered ?

See the corresponding code here : 
https://github.com/nyl-auster/yineo-front/blob/fc0a4882f6565757552dff94352089db3b0e59ff/pages/blog/index.vue

**Comment by dohomi** [comment]
@nyl-auster this might be related to https://github.com/nuxt-community/apollo-module/issues/16

**Comment by dohomi** [comment]
Closing this issue for now. Please choose the solution suggested in #16 and use your own loading indicator.

**Comment by nyl-auster** [comment]
There are still two questions i'm not sure about 

> What i expected :
> Blog posts already rendered as html string by nodejs server

> Are posts actually Server Side rendered ?

**Comment by dohomi** [comment]
@nyl-auster if you are using `prefetch` statement of vue-apollo then your query will be handled on the server and thus the initial render will have the $apollo values present. 

You will bump into server/client hydration error if the server and client differs. If not, then your code should have been rendered correctly

**Comment by nyl-auster** [comment]
@dohomi yes you are right, i edited my first post : it is the normal behavior i guess that posts are loaded "on demand" when you came from another page. So the only issue is actually the loading indicator as you described it here https://github.com/nuxt-community/apollo-module/issues/16

**Comment by dohomi** [comment]
@nyl-auster you need to wire up your own loading indicator because the official Nuxt loading depends on routing. If you have any more issues please open a separate issue.
