### ISSUE TITLE
Seeing extra payload of ssr in apollo that's not requested

### ISSUE THREAD

**Issue by tarunmangukiya** [nuxt-community/apollo-module#273]
### Version

[v4.0.0-rc.15](https://github.com/apollo-module/releases/tag/v4.0.0-rc.15)

### Reproduction link

[https://iconscout.com](https://iconscout.com)

### Steps to reproduce

1. Open chrome console and go into networks tab
2. Open https://iconscout.com
3. View and save source code of the page content.
4. Repeat Step 2 & 3 for 4-5 times
5. Observe `window.__NUXT__` object's `apollo` variable for all the cases.

You'll see different values for `defaultObject.ROOT_QUERY` which are not related to this page at all and that's changing on every request. Also, this page is not firing any graphql query at all. And it is adding extra MBs to the response. This response size varies from 1MB to 3.5MB.

You can find response at here https://drive.google.com/open?id=1AS1LUvWkiypbXluy9Pp1TfImyWsApq8L. (I was unable to attach response in here due to its size).

### What is expected ?

Usually, each request must have different cache for apollo ssr.

### What is actually happening?

I think that in here there might be cached result for some past query and which is being sent to different user in next ssr request.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c253">#c253</a>)</em></sub></div>

**Comment by tarunmangukiya** [comment]
I've seen clearing apollo cacahe `app.apolloProvider.defaultClient.cache.data.clear()` in `nuxtServerInit`, helps with this. @kieusonlam any idea about this?

Also, this issue seems there in the production, in development it's not there.

**Comment by kieusonlam** [comment]
I'll take a look at this when I have time, meanwhile if you found a solution, feel free to make a PR :)

**Comment by tarunmangukiya** [comment]
Let me try to do that. I've done as above in my production server and the response size decreased dramatically, plus memory and CPU requirement is back to half (to what it used to be). This also caused a huge memory leak for sites like us.

**Comment by tarunmangukiya** [comment]
Hi @kieusonlam, can you look at the PR https://github.com/nuxt-community/apollo-module/pull/274?
