### ISSUE TITLE
Cache not transferred from server to client on SSR

### ISSUE THREAD

**Issue by jsbroks** [nuxt-community/apollo-module#286]
### Version

[v4.0.0-rc.18](https://github.com/apollo-module/releases/tag/v4.0.0-rc.18)

### Reproduction link

[codesandbox](https://codesandbox.io/s/codesandbox-nuxt-8ofxr?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

In the code sandbox:
1. Open the console tab
2. Refresh the page (to make sure the page is rendered SSR)
3. Read the output from the console

In a project:
1. Load any apollo data on server-side
2. Read the apollo on client-side

### What is expected ?

The output of the cache on mounted to match the output of the cache on asyncData when rendered SSR 

### What is actually happening?

The output of the cache on mounted is empty.

### Additional comments?

This behavior can also be observed with any SSR render (including nuxtServerInit)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c264">#c264</a>)</em></sub></div>

**Comment by kieusonlam** [comment]
Not sure if it related to https://github.com/nuxt-community/apollo-module/pull/274

I will take a look when I got time.

**Comment by jsbroks** [comment]
I think it is. Thanks!
