### ISSUE TITLE
Package does not get updated past rc9 due to semver mismatch

### ISSUE THREAD

**Issue by pimlie** [nuxt-community/apollo-module#296]
### Version

[v4.0.0-rc.19](https://github.com/apollo-module/releases/tag/v4.0.0-rc.19)

### Reproduction link

[https://jubianchi.github.io/semver-check/#/^4.0.0-rc6/4.0.0-rc19](https://jubianchi.github.io/semver-check/#/^4.0.0-rc6/4.0.0-rc19)

### Steps to reproduce

Check the repro link. For the rc versions to work correctly a dot between rc and the number is [required](https://jubianchi.github.io/semver-check/#/^4.0.0-rc.6/4.0.0-rc.19).

As the git tags are correctly set with a dot, not sure where in the release process the dot between rc and the number is removed. Maybe you just need to add `--prerelease rc` when releasing with standard-version?

### What is expected ?

rc19 satisfies the rc6 constraint

### What is actually happening?

it doesnt

### Additional comments?

This issue causes that users will only ever be able to install `4.0.0-rc9` at the most (without manual interaction)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c276">#c276</a>)</em></sub></div>

**Comment by kieusonlam** [comment]
I unaware at this. Thanks https://github.com/nuxt-community/apollo-module/commit/70fb62864764a72c5f11d23ea4c9ce99d0f9fa57
