### ISSUE TITLE
TypeError: Cannot read property 'defaultClient' of undefined

### ISSUE THREAD

**Issue by argueta15** [nuxt-community/apollo-module#298]
I generate static project and deploy in amazon s3, when refresh page I get error:

TypeError: Cannot read property 'defaultClient' of undefined

If my project deploy in node sever it work it.

`apollo: {
    clientConfigs: {
      default: '~/plugins/apollo-config.js'
    }
  },`

`export default function (context) {
  return {
    httpEndpoint: process.env.HTTP_ENDPOINT,
    getAuth: () => {
      const token = localStorage.getItem('AUTH_TOKEN')
      if (token) {
        return `Bearer ${token}`
      } else {
        return ''
      }
    }
  }
}
`

**Comment by souljorje** [comment]
@argueta15 did u resolve this problem? If yes – please tell me, facing the same problem now.

**Comment by juanjcardona13** [comment]
@argueta15 did u resolve this problem? If yes – please tell me, facing the same problem now. X2

**Comment by janeschindler** [comment]
I also have this problem. @argueta15 please let me know if you ever resolved it. thanks!

**Comment by janeschindler** [comment]
In my case it turned out I'd accidentally updated to Nuxt 2.13 without realizing it. I rolled back to 2.11 and everything was fine again.

**Comment by souljorje** [comment]
Guys, just install v4.0.1-rc.1, it's fixed in that version https://github.com/nuxt-community/apollo-module/commit/640ba3e6e543e368cebbb0b707983e4e61856ba2.

**Comment by pencilcheck** [comment]
I'm having the issue on ^4.0.1-rc.5, what should I do?
