### ISSUE TITLE
How to create a BatchingNetworkInterface?

### ISSUE THREAD

**Issue by jvbianchi** [nuxt-community/apollo-module#3]
The current implementation uses the `createNetworkInterface` to create a normal NetworkInterface (which is fine in most cases).

But if we want to use [query batching](http://dev.apollodata.com/core/network.html#query-batching), we have to create a BatchingNetworkInterface (using `createBatchingNetworkInterface` as in [this example](http://dev.apollodata.com/core/network.html#BatchingExample).

How can we do that with this module?

**Comment by Atinux** [comment]
Should work now with 1.0 :)

See udpated README!

**Comment by astr0sl0th** [comment]
@jvbianchi  Did you ever get this working?

**Comment by adnascent** [comment]
@astr0sl0th Did you ever get this working? ;)
