### ISSUE TITLE
Cannot provide `inMemoryCacheOptions.cacheRedirects`

### ISSUE THREAD

**Issue by ozum** [nuxt-community/apollo-module#301]
### Version

[v4.0.0-rc.19](https://github.com/apollo-module/releases/tag/v4.0.0-rc.19)

### Reproduction link

[https://jsfiddle.net/35twv906/](https://jsfiddle.net/35twv906/)

### Steps to reproduce

Add `cacheRedirects` to `inMemoryCache` as seen in https://jsfiddle.net/35twv906/

See: https://www.apollographql.com/docs/react/performance/performance/

### What is expected ?

Having Apollo Cache Redirects.

### What is actually happening?

No cache redirect is happening.

Also `.nuxt/apollo-module.js` has below code. See `cacheRedirects.Query` is empty.

```js
defaultClientConfig = {
  "httpEndpoint": "http://localhost:8080/v1/graphql",
  "inMemoryCacheOptions": {
    "cacheRedirects": {
      "Query": {}
    }
  }
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c288">#c288</a>)</em></sub></div>

**Comment by domcoleman** [comment]
Have just run into this issue myself, appears to be `inMemoryCacheOptions` as whole as `dataIdFromObject` also doesn't work.

**Comment by domcoleman** [comment]
https://github.com/nuxt-community/apollo-module/blob/d6c89db7112a6b6d2645cf6ea516e0ad6fd4f04d/lib/templates/plugin.js#L30

This is what's causing the problem, as you can't stringify a function.

**Comment by domcoleman** [comment]
After taking a look this is documented already, as config will be stringified when passed in this way.
If you pass in a config file you can use functions in your config.

**Comment by ozum** [comment]
@domcoleman, I'm using TypeScript, and when I create a config file and set as below:
```js
{
  clientConfigs: {
    default: `src/apollo-config`
  }
}
```

generated apollo-module.js has `defaultClientConfig = require('src/apollo-config.ts')`, but since there isn't `src/apollo-config` in `.nuxt` directory, I'm getting `Cannot find module 'src/apollo-config.ts'`.

Any suggestions?

**Comment by domcoleman** [comment]
Use the tilde or @ character to include from the path relative to the project's root directory.

**Comment by ozum** [comment]
@domcoleman, thanks for the guidance. It solved my case.
