### ISSUE TITLE
wssLinkOptions for subscriptions?

### ISSUE THREAD

**Issue by drewbaker** [nuxt-community/apollo-module#320]
### What problem does this feature solve?

Currently we have `httpLinkOptions` but we don't have the same options for the a `wsLink` setup.

### What does the proposed changes look like?

Would be great f my config could look like this:

```
clientConfigs: {
    default: {
        wsEndpoint: "wss://localhost:4000",
        wsLinkOptions: {
            reconnect: true,
            lazy: true,
            connectionParams() {
                workspaceId: "",
                token: ""
            }
        }
    }
}
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c305">#c305</a>)</em></sub></div>

**Comment by drewbaker** [comment]
There is an old example here that I've been trying to figure out how to merge it with the current version's config, but no luck so far.
https://www.npmjs.com/package/@nuxtjs/apollo/v/3.0.4#example-with-subscription-graphcool-as-example

**Comment by dohomi** [comment]
@drewbaker the apollo-module only offers options from `vue-cli-plugin-apollo`. Please open a feature request there first before it can get implemented here.

For your current usecase you can use a custom plugin and return a `link` option rather than `httpEndpoint`
```js 
// plugins/my-alternative-apollo-config.js
export default function(context){
  // compose your link
  const link = YOUR_LINK_COMPOSITION
  return {
    link,
    getAuth:() => 'Bearer my-static-token' // use this method to overwrite functions
  }
}

// inside of nuxt config
{
 apollo:{
  clientConfig: {
    default: '~/plugins/my-alternative-apollo-config.js'
   }
 }
} 
```

**Comment by drewbaker** [comment]
Thanks @dohomi. Any tips on some reading for what my `YOUR_LINK_COMPOSITION` should be?

**Comment by drewbaker** [comment]
So after trying a few different ways, this seems like the best way. Simply overwrite the `wsClient` using a plugin.

So in `nuxt.config.js`:
```
    plugins: [
        { src: "~/plugins/apollo-ws-client.js", mode: "client" }
    ],
    apollo: {
        clientConfigs: {
            default: "~/plugins/apollo-config-default.js"
        }
    },

```

In `apollo-config-default.js`:
```
export default function() {
    return {
        httpEndpoint: "https://api.8base.com/123456",
        wsEndpoint: "wss://ws.8base.com"
    }
}

```

Then in `plugins/apollo-ws-client.js`

```
export default ({ app }) => {
    const client = app.apolloProvider.defaultClient
    const token = app.$apolloHelpers.getToken()

    if (token) {
        client.wsClient.lazy = true
        client.wsClient.reconnect = true
        client.wsClient.connectionParams = () => {
            return {
                workspaceId: "123456",
                token: token
            }
        }
    }
}
```

Works great. [Answered it here too](https://stackoverflow.com/questions/60981046/nuxt-apollo-websockets-link-options).
