### ISSUE TITLE
Nuxt fails to start when adding the package

### ISSUE THREAD

**Issue by pfritsch** [nuxt-community/apollo-module#325]
### Version

[v4.0.0-rc.19](https://github.com/apollo-module/releases/tag/v4.0.0-rc.19)

### Reproduction link

[https://codesandbox.io/s/sweet-blackwell-y4nuz?file=/package.json](https://codesandbox.io/s/sweet-blackwell-y4nuz?file=/package.json)

### Steps to reproduce

```
yarn add @nuxtjs/apollo
yarn dev
```

### What is expected ?

Nuxt (Nuxt.js v2.12.2) should start as usual

### What is actually happening?

Terminal returns :

```
 ERROR  Failed to compile with 42 errors

These dependencies were not found:
                                                    
* core-js/modules/es6.array.find in ./.nuxt/client.js, ./node_module [...]

To install them, you can run: npm install --save core-js/modules/es6.array.find  [...]
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c311">#c311</a>)</em></sub></div>

**Comment by hauptbenutzer** [comment]
I, too, ran into this today. It is because `apollo-env` depends on `core-js@3` and having both v2 and v3 seems to not work well with babel.

I was able to mitigate following the instructions outlined [here](https://github.com/nuxt/nuxt.js/issues/5287#issuecomment-567596915).

**Comment by pfritsch** [comment]
Nice, it works !

**Comment by amalhao** [comment]
@pfritsch, did you find a fix for this? I'm having the same issue.

**Comment by pfritsch** [comment]
Hi, Finally I decided to avoid using Apollo and made fetch requests otherwise.

Good luck with that

Pierre
+33 7 68 93 17 08
