### ISSUE TITLE
how to access '$apollo' from outside a vue-componenet?

### ISSUE THREAD

**Issue by ctwhome** [nuxt-community/apollo-module#328]
I am storing the user that comes from the auth provider into the database. But when the login changed it dispatches an action on the Vuex store with the details of the user. It is there where I need to call `this.$apollo.mutate, but 'this.$apollo' is not available in the store, neither this._vm.$apollo.?

Calling `this.app.apolloProvider.defaultClient` works!, but not at the time the action is triggered (at the very beginning ) 
```
 auth: {
        initialize: {
          onAuthStateChangedAction: 'user/UPSERT_USER',
        },
```
I need it to set a sleep(foo(),500) to make it work.

**Comment by eadortsu** [comment]
> I am storing the user that comes from the auth provider into the database. But when the login changed it dispatches an action on the Vuex store with the details of the user. It is there where I need to call `this.$apollo.mutate, but 'this.$apollo' is not available in the store, neither this._vm.$apollo.?
> 
> Calling `this.app.apolloProvider.defaultClient` works!, but not at the time the action is triggered (at the very beginning )
> 
> ```
>  auth: {
>         initialize: {
>           onAuthStateChangedAction: 'user/UPSERT_USER',
>         },
> ```
> 
> I need it to set a sleep(foo(),500) to make it work.

How did you get it to work, please help @ctwhome

**Comment by emmanuelvlad** [comment]
Is there a better solution?
