### ISSUE TITLE
Can this module be used together with nuxt-composition-api?

### ISSUE THREAD

**Issue by charlie0077** [nuxt-community/apollo-module#345]
Imagine you have a component like this that works perfectly. 
```
export default Vue.extend({

  apollo: {
    user: {
      query: user,
    },
  },
```

Now how to move the apollo related logic to a useXX composition API? Seems like smart query only works with apollo: {}. 
Does it even make sense to move logic like this into a composition API?

Thanks.

**Comment by negezor** [comment]
This can be achieved with `@vue/apollo-composable` https://github.com/nuxt-community/apollo-module/issues/288#issuecomment-581244070

**Comment by szvest** [comment]
As @negezor said. `@vue/apollo-composable` uses the composition functions `useQuery` and `useResult`. The latter allows you picking one object from the result data.

```
import { useQuery, useResult } from '@vue/apollo-composable'
```
```
export default {
  setup () {
    const { result } = useQuery(gql`
      query getItems {
        items {
          id
          name
        }
      }
    `)
    return {
      result,
    }
  },
}
```

The [docs are here](https://v4.apollo.vuejs.org/guide-composable/) for more details and use cases.

**Comment by charlie0077** [comment]
thanks.
