### ISSUE TITLE
Token expiry / refresh tokens

### ISSUE THREAD

**Issue by gino** [nuxt-community/apollo-module#354]
Hi,

Access tokens are usually, cause of safety purposes, set to have an expiration date. For example, an access token expires after 30 minutes and a refresh token will be used to generate a new access token. Unfortunately I do not see how I am able to achieve this. It looks like it is necessary to have an access token with no expiration or is it possible to achieve this with refresh tokens?

Cause my access token obviously expires after ~30 minutes, and I do not wanna force the user to login every 30 minutes. And I do not wanna create an access token that has no expiration date at all, this would not be safe.

Is there anyone else that is experiencing the same issue and knows how I am able to fix this?

Thanks a lot.

**Comment by dargmuesli** [comment]
Why did you close this issue? :)

**Comment by idunforge** [comment]
@gino did you solve it??
