### ISSUE TITLE
Multiple clients results in Duplicate declaration "networkInterface"

### ISSUE THREAD

**Issue by bjunc** [nuxt-community/apollo-module#36]
It looks like the use of `let networkInterface` and `const opts` will throw errors if there is more than one client assigned.  They either need to be wrapped in a block (to isolate scope), or use `var` (quick fix to get it working again).

**Comment by dohomi** [comment]
@bjunc I don't have a usecase for mutliple clients. can you open a PR for this? Thanks!

**Comment by bjunc** [comment]
@dohomi happy to submit a tweak that I think should make it work.

FYI, my particular use-case is that I am connecting to an GraphQL server over both HTTP for conventional request/response, as well as through a socket for pubsub.  It would be nice to be able to only run the socket (negating the need for two network interfaces), but I had problems running the socket libs server-side (I think one of them is calling `window`).  Until I figure out the culprit, I figured I'd use the HTTP interface server-side, and the socket interface in the browser.

Anyway, I'll submit a PR.

**Comment by bjunc** [comment]
@dohomi just a heads up, but I'm having a hard time connecting a socket with `v2.1+`.  I was able to get it working with `v2.0.0`.  For some reason, `2.0.0` isn't using `HTTPFetchNetworkInterface`, whereas `v2.1+` is.  In that event, the socket connection info gets overwritten.  Both `2.0.0` and `2.1.1` have issues with multiple clients, but since they're slightly different logic, I need to figure out the socket issues first, then I can upgrade to `2.1.1`, then fix the multiple clients issue.

**Comment by dohomi** [comment]
@bjunc Ok let me know if you have any further questions. I use 2.1.1 with one client and graph.cool backend without any issues. there were only very few differences from 2.0.0 => 2.1.1 but lets get this working for you

**Comment by bjunc** [comment]
@dohomi thanks.  I think the 2.0.0 vs 2.1.1 issue might have had more to do with Apollo, than this module.  Hard to tell sometimes with so many nested dependencies.  I ended up building my own network interface, which solved that problem ([phoenix websocket network interface](https://github.com/bjunc/phoenix-websocket-network-interface)).  Ultimately, that allowed me to use one socket based network interface for both server and browser environments. However, I'm happy to help by submitting a PR for allowing multiple apollo clients; since it might help someone else.  I'll do that tonight.

**Comment by dohomi** [comment]
@bjunc great news that it worked out for you. Soon apollo v2 is going to be released, I guess there will be some refactoring needed as well
