### ISSUE TITLE
Apollo composables not working

### ISSUE THREAD

**Issue by ruslansteiger** [nuxt-community/apollo-module#363]
### Version

[v4.0.1-rc.4](https://github.com/apollo-module/releases/tag/v4.0.1-rc.4)
@nuxtjs/composition-api@0.13.5
@vue/apollo-composable@4.0.0-alpha.12

### Reproduction link

[https://github.com/SuddenlyRust/nuxt-apollo-composables](https://github.com/SuddenlyRust/nuxt-apollo-composables)

### Steps to reproduce

`yarn dev`

visit `http://localhost:3000/`

### What is expected ?

Working application without error messages

### What is actually happening?

`ReferenceError: define is not defined` is shown

![bug.png](https://cmty.s3.eu-west-1.amazonaws.com/98543958/f5436920-11e9-11eb-9303-cf2b645c63a8.png)

### Additional Information

With **@vue/apollo-composable@4.0.0-alpha.10** this error message is not shown.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c340">#c340</a>)</em></sub></div>

**Comment by seanaye** [comment]
I am getting same issue. Is downgrading to alpha 10 the only known fix?

EDIT: This is an issue with vue-apollo-composable not the nuxt-apollo module. I am not using nuxt and am receiving the exact same error

**Comment by seanaye** [comment]
The root of the issue is https://github.com/vuejs/vue-apollo/issues/1081

**Comment by YankeeTube** [comment]
@seanaye   `alpha 10` same issue

**Comment by ruslansteiger** [comment]
Got it working with the transpilation workaround: https://github.com/vuejs/vue-apollo/issues/1081#issuecomment-772562609

Check out my commit: https://github.com/SuddenlyRust/nuxt-apollo-composables/commit/e09bce74141af50d6b5d96eed072a102c06a6ec7
