### ISSUE TITLE
how to do pagination with apollo

### ISSUE THREAD

**Issue by iisalazar** [nuxt-community/apollo-module#377]
So far I can't find any example anywhere on how to do pagination with nuxt + apollo. I found some, but it only seems to be graphql-specific. 

Please help, thanks.

**Comment by sabanworld** [comment]
Hey, Apollo is a way over interacting with a graphql api. So all examples will indeed be graphql related. Look up "Apollo Smart Query" and view the variables section. You will basically be utilising your graphql query with variables you use in your query as page, offset, limit (depending on your pagination implemented).

**Comment by iisalazar** [comment]
You're right, and I found a solution my problem by looking up docs of vue-apollo. Basically they abstracted Apollo's Smart query by providing their own function ```fetchMore()```, [here's the docs for it](https://apollo.vuejs.org/guide/apollo/pagination.html).
