### ISSUE TITLE
compatibility branch for vue-apollo 3.x

### ISSUE THREAD

**Issue by dohomi** [nuxt-community/apollo-module#38]
Need to work on a compatibility version for vue-apollo 3.x and apollo-client 2.x

@Akryum it would be great to catch up on this issue together. Thanks!

**Comment by Akryum** [comment]
The main difference would be that there is no longer a network interface. We should probably expect an Apollo Link and an Apollo Cache objects from the module user.

**Comment by Hendrixer** [comment]
@Akryum not rushing, but asking for an update. I need this for a project and have no problem updating it myself. But if you're about to release the update in the next day or so, I can wait.

**Comment by dohomi** [comment]
@Hendrixer any PR is welcome. I haven't got the time yet to work on it

**Comment by Hendrixer** [comment]
@dohomi PR is up #39
