### ISSUE TITLE
Latest Nuxt Composition API is not working

### ISSUE THREAD

**Issue by ruslansteiger** [nuxt-community/apollo-module#383]
### Version

[v4.0.1-rc.5](https://github.com/nuxt-community/apollo-module/releases/tag/v4.0.1-rc.5)
@nuxtjs/composition-api@0.19.1
@vue/apollo-composable@4.0.0-alpha.10

### Reproduction link

[https://github.com/SuddenlyRust/nuxt-apollo-composition-api](https://github.com/SuddenlyRust/nuxt-apollo-composition-api)

### Steps to reproduce

`yarn install`

 `yarn dev`

Visit `http://localhost:3000/`

### What is expected ?

Working application without error message.

### What is actually happening?

Following error shown: `Cannot read property '_apolloAppTracking' of undefined`

![error.png](https://cmty.s3.eu-west-1.amazonaws.com/98543958/07043000-6de7-11eb-abae-eb614faf0ff9.png)

### Additional comments?

Downgrading to `@nuxtjs/composition-api@0.17.0` does fix it!

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c365">#c365</a>)</em></sub></div>

**Comment by jsbroks** [comment]
https://github.com/vuejs/vue-apollo/issues/1029#issuecomment-759775227

https://github.com/vuejs/vue-apollo/issues/1029#issuecomment-759778105

Had this same issue

**Comment by mvanalphen** [comment]
I ran into this issue as well, but after upgrading to `@vue/apollo-composable@4.0.0-alpha.12` the issue was resolved. This does however required this transpilation workaround: https://github.com/vuejs/vue-apollo/issues/1081#issuecomment-772562609.

**Comment by ruslansteiger** [comment]
Thank you @mvanalphen. The transpilation workaround is working 🚀

Check out following commit for a working version: https://github.com/SuddenlyRust/nuxt-apollo-composition-api/commit/10a577e9a6988991ca44cdfe50d7e43e2beccf1a
