### ISSUE TITLE
Upload mutation - file stream is 0 bytes - file not in POST

### ISSUE THREAD

**Issue by jrcichra** [nuxt-community/apollo-module#392]
My original cmty post, issue was never propagated to Github issues: https://cmty.app/nuxt/apollo-module/issues/c368

I have a mutation that should upload a file but doesn't. The attachment size is bigger than what the 'Network' tab shows, so the picture must not be in the POST.

Full source tree at question commit: https://github.com/jrcichra/loxodonta/tree/5b463103b3e3902b16fb259d8e852cf8c24765f0
You can recreate the problem with docker-compose build && docker-compose up and go to http://localhost:3000. Pick a file and look at the network tab.

Form:
```
        <b-form inline @submit="newFile">
          <b-form-file v-model="form.attachments" accept=".jpg, .png, .gif">
          </b-form-file>
          <b-button type="submit" class="postbutton">Post</b-button>
        </b-form>
```
data():
```
  data() {
    return {
      username: "Justin",
      placeholder: "What's on your mind?",
      form: {
        text: "",
        attachments: [],
      },
    };
  },
```
Method:
```
    async newFile(event) {
      event.preventDefault(); //Don't submit the page
      var file = this.form.attachments;
      if (file) {
        console.log(file);
        try {
          await this.$apollo
            .mutate({
              mutation: newfile,
              variables: {
                file,
              },
            })
            .then(({ data }) => console.log(data));
        } catch (e) {
          console.error(e);
        }
      } else {
        console.error("attachments were not defined but newFile was called");
      }
    },
```
Mutation client-side:
```
mutation newFile($file: Upload!) {
    newFile(file: $file) {
        filename
        mimetype
        encoding
    }
}
```
nuxt.config.js:
```
    apollo: {
        clientConfigs: {
            default: {
                httpEndpoint: 'http://localhost:3001/graphql',
            }
        }
    },
```
According to https://github.com/nuxt-community/apollo-module/issues/259, apollo-upload-client is already implemented. What am I missing? Thanks.

Screenshots:
![image](https://user-images.githubusercontent.com/1342149/114258739-c853a080-9996-11eb-8b15-e99f2b314814.png)
![image](https://user-images.githubusercontent.com/1342149/114258746-cee21800-9996-11eb-909d-092fe2995cfb.png)

**Comment by RoMay** [comment]
Had a similar issue. This was helped me out: https://stackoverflow.com/questions/64658321/variable-file-got-invalid-value-upload-value-invalid/64659256#64659256
