### ISSUE TITLE
Seeking debugging advice

### ISSUE THREAD

**Issue by ndarilek** [nuxt-community/apollo-module#40]
Hitting a very strange issue and am seeking advice on how to debug this. I'm creating a network interface like so:

```
import {createNetworkInterface} from "apollo-phoenix-websocket"

let host = process.browser ? location.origin.replace(/^http/, "ws") : "ws://127.0.0.1:4000"
if(process.browser)
  host = host.replace("3000", "4000")

export default () => createNetworkInterface({
  uri: `${host}/socket`
})
```

This function definitely gets called and returns an interface, but my requests are sent over HTTP to a /graphql endpoint on 3000 rather than to the Phoenix websocket at /socket on port 4000. Further, when I do:

```
  mounted() {
    console.log("Mounted", this.$apollo.provider.clients.defaultClient.networkInterface)
  },
```

in a component, I see a network interface with /graphql as the URI. Something somewhere seems to be creating a default network interface, guessing that my GraphQL endpoint is at localhost:3000/graphql rather than at localhost:4000/socket where my interface explicitly points, but I can't find what that might be.

My thought was to check out the raw module source into node_modules and start adding console.logs, but I see lines like:

```
    <% if (key === 'default') { %>
```

I don't immediately see how to run code with these templating lines in it. Is there some preprocessing step I have to run to add debugging code into the module?

Failing that, is there some known place in the code where a network interface with a /graphql URI might be created? My backend has its endpoint at either localhost:4000/api or localhost:4000/socket, so nowhere am I creating this.

To be clear, I don't think the issue is in this module, but this module is where I'd start to debug the problem, and while I see these template lines throughout the Nuxt code, nowhere do I see an explanation of what they are.

Thanks.

**Comment by ndarilek** [comment]
FWIW, pretty sure I'm hitting [this issue](https://github.com/vic/apollo-phoenix-websocket/issues/26), so what I'm experiencing here isn't a problem in this module. But I'd definitely be interested in how to debug templated code like this, and as there isn't an easily found support channel for the Nuxt ecosystem, I'm asking here. Sorry if that isn't correct on my part.

**Comment by dohomi** [comment]
@ndarilek please upgrade to the newest version of this module which makes use of apollo-client v2. I think you will find the best support in the apollo-client community thus this package is just a wrapper to provide their functionality as an easy integration into Nuxt
