### ISSUE TITLE
Unable to use Nuxt's error/redirect functionality when a query failed

### ISSUE THREAD

**Issue by ciscorn** [nuxt-community/apollo-module#42]
I want to call the `context.error({...})` to show the Nuxt's error page when a query failed (Item not found, etc.).

In `asyncData(context) {...}`, we can easily do that as `context` is always given.

However inside vue-apollo's smart queries, I can't find a way to access the `error()`

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/apollo-module/issues/c30">#c30</a>)</em></sub></div>

**Comment by ciscorn** [comment]
I just found that I can access the `error` function via `this.$root` in server-side.

Is it the right (or stable) way?

```js
  apollo: {
    entry: {
      query: ENTRY_QUERY,
      error() {
        this.$root.error({'statusCode': 404, 'message': 'OK'})
      },
      variables: {
          // ...
      },
      prefetch: true,
    }
  },
```

**Comment by dohomi** [comment]
Hi @ciscorn 

I think there are several ways of doing it. I prefer to redirect the user inside of the result hook. But your way is also a possible way of doing it

**Comment by ciscorn** [comment]
@dohomi I noticed that my code above (and your suggestion) doesn't work in SSR because the `result` and `error` handler are evaluated after SSR has done.

**Comment by dohomi** [comment]
@ciscorn yes we discovered this. Its something you can track inside of vue-apollo it has not necessary something todo with this package.

Try wrap your code in 
```
result({data}){
  this.$nextTick(() => {
     // here you can set context to your component
  })
}
```

**Comment by dohomi** [comment]
Sorry I think I misread your question. Maybe @Akryum has a good idea how to solve this, I always wait for the result and then redirect the user to error pages

**Comment by ciscorn** [comment]
@dohomi Thanks. I think something (such as `prefetchResult` handler) should be implemented on vue-apollo to serve real 404/302 pages in SSR.

**Comment by dohomi** [comment]
@ciscorn please open an issue inside of `vue-apollo` package. This package just supersets the usage of vue-apollo and will not add any features to extend vue-apollo

**Comment by ciscorn** [comment]
Please ignore if this is irreverent.

I created a modified version of apollo-module just for testing.

https://github.com/ciscorn/apollo-explicit-module

It solves the error/redirect problem and a (potential) concurrency problem without any modifications of Nuxt and vue-apollo. (However it introduces breaking changes.)

Please read a brief explanation in my README.md.

**Comment by dohomi** [comment]
@ciscorn what happens if you use:
```
  async fetch(context) {
    const result = await contxt.app.apolloProvider.defaultClient.query(YOUR_QUERY_OBJECT)
    // You can call context.error (or redirect) based on the result
  },

 //! without any apollo...
```
with this package? I do this on some parts and had no issues so far.

**Comment by ciscorn** [comment]
@dohomi @Akryum 

Nuxt.js has a built-in functionality to return 404/403/302/301 responses with `context.error(...)` and `context.redirect(...)`. However in the original `@nuxtjs/apollo`, prefetching is performed after the Nuxt has finished checking the error/redirect flags, so the Nuxt's `context.error` doesn't work with apollo-module.

(I think #35 is a bit related to the same problem.)

Using my modified version, I can return "real 404/403" responses to clients. I think this is an important aspect of SSR. Redirecting to /404 page or something are not beautiful. We should be able to return 404/403/etc without URL changes and should be able to return error status codes directly (as Nuxt.js kindly supports this.)

```js
  async fetch({app, error}) {
    const prefetchResult = await app.apolloPrefetch(this)
    if (!prefetchResult.article.data.article) {
      error({statusCode: 404, message: "Item Not Found"})
    }
  },
```

![404](https://user-images.githubusercontent.com/5351911/33008607-18790310-ce17-11e7-941a-f6b5459eb6bc.jpg)

**Comment by dohomi** [comment]
@ciscorn ok I understand now better. @Akryum what do you think about this approach?

**Comment by dohomi** [comment]
@kavalcante @ciscorn haven't had this implementation on my radar yet. You can gain same result with following code:
```js
async asyncData({error, app, params}){
  const article = await app.apolloProvider.defaultClient.query({
    query: `someGql`,
    variables:{id: params.id}
  }).then(({data}) => data && data.Article)
  if(!article){
    return error({statusCode: 404, message: 'Not found'})
  }
  return {article}
}
```
Is there any reason why not using `asncData` directly, you would write actually less code to receive the same result. Setting up a fetch method is slightly redundant in my eyes. I'm not sure if its straight forward to decouple the query call and add the fetch statement to it. @Akryum I'd still be interested if you have any opinion as you have better knowledge in the `vue-apollo` client.

**Comment by JRobber** [comment]
@dohomi One major reason to do ciscorn's implementation is that with your solution I have to do a query.   Given this basic example of routing : 

Pages
/product
   _id.vue

The query is always sent before I can validate or asyncData (fetch isn't even invoked SSR).  All I'd like to do is if there is no param provide re-route to the home page or something, but I can't if apollo is included in the component.  It maybe a bug in vue-apollo and I'm going to go submit it there as well.  But it makes sense here because nuxt includes server side and can pre-empt the query on an in-valid url.

**Comment by ciscorn** [comment]
My solution is a kind of dirty hack to avoid using [beforeNuxtRender](https://github.com/nuxt/nuxt.js/blob/fb978b812a3790f3e0be386931a75662e6903fe5/lib/app/server.js#L210).

It would be the best if we can set up a hook [here](https://github.com/nuxt/nuxt.js/blob/fb978b812a3790f3e0be386931a75662e6903fe5/lib/app/server.js#L196).

**Comment by dohomi** [comment]
As version 4 follows now a different approach I will close this issue. Most likely it does not solve your issue but maybe the best way would be to run a separate module for it.

**Comment by aaronransley** [comment]
@dohomi, you mention a new approach as of version 4, but I'm not sure where to find more information on that approach. Would you mind pointing me towards some docs?

Thanks for all your work on @nuxtjs/apollo!

**Comment by dohomi** [comment]
@aaronransley whats the exact issue you are facing?

**Comment by mccxiv** [comment]
I see this issue is closed, does that mean [smart queries](https://github.com/Akryum/vue-apollo/blob/master/docs/api/smart-query.md) are officially discouraged in favor of asyncData? 

Right now I don't see a way to set the HTTP status code from the server side using a smart query, so instead we must use `context.app.apolloProvider.defaultClient.query`; definitely less elegant

**Comment by sebmor** [comment]
+1 Definitely would like to see this in the smart query as well.

**Comment by jsbroks** [comment]
It is also important to note that if you using asyncData, the the data will not update with mutations.
