### ISSUE TITLE
Can an example be made for Nuxt with subscriptions?

### ISSUE THREAD

**Issue by lolcoolkat** [nuxt-community/apollo-module#43]
Can someone please make an official example using subscriptions with the new v3 :)

Can't seem to get it working with v2.1.1 :( Thank you

**Comment by dohomi** [comment]
@lolcoolkat your question should be better posted in https://github.com/Akryum/vue-apollo, this package is just the wrapper for vue-apollo code

**Comment by dohomi** [comment]
Personally I don't use subscriptions but happy if someone would provide some code to extend the README

**Comment by rnenjoy** [comment]
Yes this only has the httpLink. How would it look like with a subscription ws link?

https://www.apollographql.com/docs/link/links/ws.html

**Comment by rnenjoy** [comment]
This is my clientDefault config file:

`import { HttpLink } from 'apollo-link-http'
import { InMemoryCache } from 'apollo-cache-inmemory'
import { WebSocketLink } from 'apollo-link-ws'
import { SubscriptionClient } from 'subscriptions-transport-ws'

export default (ctx) => {
  let link = null

  if (ctx.isServer) {
    link = new HttpLink({ uri: 'http://localhost:3000/graphql' })
  } else {
    const client = new SubscriptionClient('ws://localhost:3001/graphql', {
      reconnect: true
    })

    link = new WebSocketLink(client)
  }

  const cache = new InMemoryCache()

  return {
    link,
    cache
  }
}
`

**Comment by dohomi** [comment]
@rnenjoy does your code work in your application?

**Comment by rnenjoy** [comment]
Yes dude. Works great! Fixed it last night. Need more help?

**Comment by dohomi** [comment]
@rnenjoy nope just asking I might extend our README with your ws example so great that you make it work

**Comment by dohomi** [comment]
By the way, here a current example for Angular 2 just in case someone wants to adopt some code: https://alligator.io/angular/graphql-subscriptions/

**Comment by dohomi** [comment]
Example is updated in the README
