### ISSUE TITLE
Send the JWT tokens as part of the Authorization header

### ISSUE THREAD

**Issue by eduayme** [nuxt-community/apollo-module#441]
I am trying to send the JWT token as part of the authorization header but I coudn't find it on the official docs or on any forum. Is there any way to do it?

**Comment by Diizzayy** [comment]
If your using the new `v5` for nuxt 3, the [`onLogin` helper function](https://apollo.nuxtjs.org/getting-started/auth-helpers#onlogin) is what you're looking for

**Comment by eduayme** [comment]
Thanks @Diizzayy.  I have try it and ti works fine. I think you should consider adding the [GitHub example](https://github.com/nuxt-modules/apollo/wiki/3.-Usage) in the official docs as I used these ones to make it work.

**Comment by Diizzayy** [comment]
> I have try it and ti works fine

@eduayme Happy to hear it works for you, and certainly, a big update to the documentation is around the corner.
