### ISSUE TITLE
Link in issue template leads you to a porn site

### ISSUE THREAD

**Issue by mikehaertl** [nuxt-community/apollo-module#446]
The link you have in your issue template leads me to a porn site.

https://github.com/nuxt-modules/apollo/blob/1f52586ab7ae3944b0cbfccc01c893ca3c9c8df9/.github/ISSUE_TEMPLATE.md?plain=1#L4

**Comment by Diizzayy** [comment]
@mikehaertl Thank you for pointing this out.
