### ISSUE TITLE
Remove authType in nuxt.config

### ISSUE THREAD

**Issue by alessioraggioli** [nuxt-community/apollo-module#448]
### Environment

"@nuxtjs/apollo": "^5.0.0-alpha.3"

### Describe the bug

Hi, I tried to remove the default "Bearer" authType, reading the documentation here: 
https://apollo.nuxtjs.org/getting-started/configuration#authtype
`apollo: {
    clients: {
      default: {
        httpEndpoint: process.env.GRAPHQL_URL,
        authType: "",
      }
    }
  }`

But seems not working, in the request headers i always get
Authorization: Bearer <token>

### Expected behaviour

I need to remove the default bearer value, keep just the token.

**Comment by Diizzayy** [comment]
@alessioraggioli try setting `authType` to `null`

**Comment by alessioraggioli** [comment]
Tried 
```
apollo: {
    clients: {
      default: {
        httpEndpoint: process.env.GRAPHQL_URL,
        authType: null,
      }
    }
  }
```

It set me the default "Bearer" in network auth..

**Comment by alessioraggioli** [comment]
@Diizzayy how can i get the fix? just reinstalling yarn package?

**Comment by Diizzayy** [comment]
> how can i get the fix? just reinstalling yarn package?

@alessioraggioli Indeed, update to `v5.0.0-alpha.4` for the fix to take effect.
