### ISSUE TITLE
Apollo not working on vue 3.0.0-rc.13

### ISSUE THREAD

**Issue by drucinsky** [nuxt-community/apollo-module#449]
Hello i install nuxt/apollo and i add modules to nuxt.config.ts but when i configure apollo i have this error.
![image](https://user-images.githubusercontent.com/47297126/201220706-0b249660-bcb8-457a-a0b9-944dc159c789.png)
How can fix it?

**Comment by Diizzayy** [comment]
@drucinsky I suspect that may just be due to the pertinent types for the module not being generated as yet. Are there errors logged to the console when you start the development server?

**Comment by jowax** [comment]
I had the same problem and got it working by first generating the types by starting the dev server and then restarting the typescript language server.

![image](https://user-images.githubusercontent.com/8604164/201466183-c959820a-9320-4d02-9fe8-44969ab28a5c.png)

**Comment by drucinsky** [comment]
Restart TS server working, thanks!
