### ISSUE TITLE
These dependencies were not found

### ISSUE THREAD

**Issue by kieusonlam** [nuxt-community/apollo-module#45]
I have error when try `apollo-module`. Here is my full error

```
ERROR  Failed to compile with 5 errors                                                                                       14:34:28
These dependencies were not found:

* apollo-link-http in ./apollo/client-configs/default.js
* graphql/language/printer in ./node_modules/apollo-cache-inmemory/lib/writeToStore.js, ./node_modules/apollo-client/index.js and 2 others

To install them, you can run: npm install --save apollo-link-http graphql/language/printer
```

Any idea?

By the way, I'm using Windows 10 - Node 8.9.1

**Comment by abattenburg** [comment]
@kieusonlam Can you tell me how you solved this? I'm running into the same issue when trying to upgrade to 3.0.

**Comment by kieusonlam** [comment]
@abattenburg You have to install dependencies by your own. You can run 
`npm install --save apollo-link-http graphql`
and it should be work.
