### ISSUE TITLE
After updating to Nuxt 3, gql is not defined

### ISSUE THREAD

**Issue by alessioraggioli** [nuxt-community/apollo-module#453]
### Environment

^5.0.0-alpha.4

### Describe the bug

Hi, I have updated my project to nuxt 3, these are the packages i'm using:

"@nuxtjs/apollo": "^5.0.0-alpha.4",
"nuxt": "3.0.0"

after the updating i got the error: "gql is not defined", calling this function

_export function GQL_signAuth(payload) {
  return gql`
    mutation {
      signAuth(
        ticketSso: "${payload.token}"
        product: 12
        acl: [sso, provisioning]
      ) {
        ticketSso
        jwt
        profile
        roles
      }
    }
  `
}_

### Expected behaviour

gql query working

**Comment by art-boer** [comment]
@alessioraggioli graphql-tag is a dev dependency of this project, so you would have to install it within your own project.

**Comment by joshistoast** [comment]
@art-boer just installed `graphql-tag` via `pnpm add graphql-tag` but the issue persists. Are there any additional steps that need to be taken or preferred method of installation?

**Comment by joshistoast** [comment]
### UPDATE
Moving `@nuxtjs/apollo` to my dev dependencies seemed to have done the trick 👍
