### ISSUE TITLE
useAsyncQuery clientId parameter doesn't work

### ISSUE THREAD

**Issue by artm4r** [nuxt-community/apollo-module#455]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `plugins`, `modules`, `apollo`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`, `@nuxtjs/apollo@5.0.0-alpha.4`
- Build Modules:    `-`

### Describe the bug

`useAsyncQuery(GetComentsForHome, 'reviews')` uses the 'default ' client even though I specified a different client.
`useQuery(GetComentsForHome, { clientId: 'reviews' })` works fine.

### Expected behaviour

I expect module to use specified client instead of default

**Comment by artm4r** [comment]
`const { data } = await useAsyncQuery({
  query: GetComentsForHome,
  clientId: 'reviews',
})`
this syntax works, but this solution is not quite obvious

**Comment by lewebsimple** [comment]
I can confirm this, as I'm getting the same behaviour !

**Comment by slavanossar** [comment]
Was also experiencing this, looking at the typings shows the different ways to pass parameters to `useAsyncQuery`

```ts
type TQuery<T> = QueryOptions<OperationVariables, T>['query'];
type TVariables<T> = QueryOptions<OperationVariables, T>['variables'];
type TAsyncQuery<T> = {
    query: TQuery<T>;
    variables?: TVariables<T>;
    key?: string;
    cache?: boolean;
    clientId?: string;
};
export declare function useAsyncQuery<T>(opts: TAsyncQuery<T>): AsyncData<T, Error>;
export declare function useAsyncQuery<T>(query: TQuery<T>, clientId?: string): AsyncData<T, Error>;
export declare function useAsyncQuery<T>(query: TQuery<T>, variables?: TVariables<T>, clientId?: string): AsyncData<T, Error>;
```

So for the following

```ts
const { data } = useAsyncQuery<MyQueryType>(
  MyQueryDocument,
  {
    someVariable: 'abc',
  },
  'myApolloClient'
)
```

you can rewrite it as

```ts
const { data } = useAsyncQuery<MyQueryType>({
  query: MyQueryDocument,
  variables: {
    someVariable: 'abc',
  },
  clientId: 'myApolloClient'
})
```

and it will work correctly.
