### ISSUE TITLE
"apollo:error" hook not working on production

### ISSUE THREAD

**Issue by maniek335** [nuxt-community/apollo-module#461]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@3.3.0`
- Builder:          `vite`
- User Config:      `modules`, `apollo`, `googleFonts`, `turnstile`, `srcDir`
- Runtime Modules:  `@formkit/nuxt@1.0.0-beta.9-f64c966`, `@nuxtjs/apollo@5.0.0-alpha.4`, `@nuxtjs/google-fonts@3.0.0-1`, `@nuxtjs/tailwindcss@6.1.3`, `nuxt-icon@0.1.7`, `nuxt-turnstile@0.1.1`
- Build Modules:    `-`

### Describe the bug

In the [documentation](https://apollo.nuxtjs.org/recipes/error-handling) is the description "apollo:error" hook. I thought this would allow me to handle jwt token expiration errors globally. But I found a condition in the [code](https://github.com/nuxt-modules/apollo/blob/176db256287f74229e94648eeb15337e030ccf44/src/runtime/plugin.ts#L87) to disable the hook in production.

### Expected behaviour

After building the application, I expect the working "apollo:error" hook.

**Comment by Diizzayy** [comment]
> But I found a condition in the [code](https://github.com/nuxt-modules/apollo/blob/176db256287f74229e94648eeb15337e030ccf44/src/runtime/plugin.ts#L87) to disable the hook in production.

Indeed, I'll release an update shortly addressing this issue
