### ISSUE TITLE
No Cache Data available

### ISSUE THREAD

**Issue by thibault60000** [nuxt-community/apollo-module#472]
### Environment

Nuxt 3 project 

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `ssr`, `css`, `build`, `runtimeConfig`, `app`, `postcss`, `i18n`, `apollo`, `modules`
- Runtime Modules:  `@nuxtjs/apollo@5.0.0-alpha.5`, `@nuxtjs/tailwindcss@6.3.0`, `@nuxtjs/i18n@8.0.0-beta.9`, `@pinia/nuxt@0.4.6`
- Build Modules:    `-`
------------------------------

### Describe the bug

I don't have data writted on the Apollo Cache
with the nuxt config : 

```
	clients: {
			default: {
				authType: 'Bearer', // Default
				authHeader: 'Authorization', // Default,
				tokenStorage: 'cookie', // Default and required for SSR
				httpEndpoint: 'http://localhost:1500/api/graphql',
				httpLinkOptions: {
					fetchOptions: {
						mode: 'cors',
					},
				},
				connectToDevTools: true, // Default
			},
		},
	},
```

I used `useLazyAsyncQuery` on my vue component
But on the plugin I don't have cache data :/ 

<img width="373" alt="Capture d’écran 2023-02-02 à 22 53 01" src="https://user-images.githubusercontent.com/18366294/216457889-daec876e-b2be-464b-b979-5f997530a39f.png">

And I have 0 query, 0 mutation

But if I try a query on the plugins apollo playground, I have 1 query but 0 cache data

<img width="373" alt="Capture d’écran 2023-02-02 à 22 54 29" src="https://user-images.githubusercontent.com/18366294/216458119-d4ba97ba-bb27-401a-93ee-67213c891981.png">

### Expected behaviour

I want to save my query data by default on the Apollo Cache

### Reproduction

```
const { data, pending, error } = await useLazyAsyncQuery(query, variables, {
	fetchPolicy: 'cache-first',
})
``` 

or just
```
const { data, pending, error } = await useLazyAsyncQuery(query, variables)
```

**Comment by matiyin** [comment]
+1 i experience the same all the same versions and setup excluding tailwind. Keeps reloading the data of each page and no caching is done.
Same result with useQuery.

**Comment by keithmifsud** [comment]
+1 Cannot even see the Apollo tab in dev tools.

**Comment by yazer79** [comment]
no update on this?
