### ISSUE TITLE
Failed to resolve import "@vue/apollo-composable" from "pages/login.vue". Does the file exist?

### ISSUE THREAD

**Issue by leonceaklin** [nuxt-community/apollo-module#477]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.1`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `components`, `modules`, `i18n`, `apollo`, `build`, `vite`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.9`, `@nuxtjs/apollo@5.0.0-alpha.5`
- Build Modules:    `-`

### Describe the bug

The @vue/apollo-composable is not found.

### Expected behaviour

Nuxt apollo installs @vue/apollo-composable correctly

### Reproduction

1. Install @nuxtjs/apollo@5.0.0-alpha.5 in a nuxtjs project
2. Use for example `useMutation` inside a vue component.
3. See the error when opening the page

### Logs

```shell
ERROR  1:19:44 PM [vite] Internal server error: Failed to resolve import "@vue/apollo-composable" from "pages/login.vue". Does the file exist?
  Plugin: vite:import-analysis
  File: pages/login.vue:4:30
  2  |  import { ref } from 'vue';
  3  |  import { gql } from 'graphql-tag';
  4  |  import { useMutation } from '@vue/apollo-composable';
     |                               ^
  5  |  const _sfc_main = {
  6  |    __name: 'login',
      at formatError (/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41235:46)
      at TransformContext.error (/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41231:19)
      at normalizeUrl (/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:39540:33)
      at async TransformContext.transform (/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:39673:47)
      at async Object.transform (/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41506:30)
      at async loadAndTransform (/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:39313:29)
```

**Comment by leonceaklin** [comment]
I can install @vue/apollo-composable (only when I'm using --force) manually. But this shouldn't be necessary, or should it?

**Comment by leonceaklin** [comment]
Also, after installing @vue/apollo-composable manually. I get this error as soon as the mutation gets called in the component: `Apollo client with id default not found. Use provideApolloClient() if you are outside of a component setup.`, even though I set it up like this:
`apollo: {
    clients: {
      default: {
        httpEndpoint: "/graphql"
      }
    },
  },`

I'm not sure if this error is a result of installing `@vue/apollo-composable` manually.

**Comment by guendev** [comment]
Follow this comment to resolve the missing default client https://github.com/nuxt-modules/apollo/issues/444#issuecomment-1354571194

**Comment by leonceaklin** [comment]
Thanks! It works for me now.
