### ISSUE TITLE
No data after fetching 

### ISSUE THREAD

**Issue by kuraiconnect** [nuxt-community/apollo-module#478]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `runtimeConfig`, `apollo`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `@nuxtjs/apollo@5.0.0-alpha.5`
- Build Modules:    `-`

### Describe the bug

i have a problem with data fetching.

click login for get access token

pick apollo or fetch for fetching data

when i try to fetch data with useQuery. After that i fetch data in network -> preview
<img width="464" alt="Screenshot 2023-02-07 at 19 25 57" src="https://user-images.githubusercontent.com/112625938/217288297-3a8a631a-c014-4088-a217-0afaba82e0b0.png">

but useQuery do not show this data:
<img width="198" alt="Screenshot 2023-02-07 at 19 25 01" src="https://user-images.githubusercontent.com/112625938/217288179-a0393b0f-3439-4e3e-a7c6-450331d8c8c0.png">

i try fetch data with $fetch and it's work
<img width="299" alt="Screenshot 2023-02-07 at 19 25 06" src="https://user-images.githubusercontent.com/112625938/217288257-0804d3b9-1b91-4c9d-bb9c-c9911c9d1e3c.png">

but it is not best. 

how i can fix it?

### Expected behaviour

i would like to get the correct data with useQuery

### Reproduction

https://codesandbox.io/p/sandbox/beautiful-artem-u0uohu?selection=%5B%7B%22endColumn%22%3A40%2C%22endLineNumber%22%3A13%2C%22startColumn%22%3A40%2C%22startLineNumber%22%3A13%7D%5D&file=%2Fpages%2Findex.vue

**Comment by Baroshem** [comment]
I am experiencing the same problem :(

**Comment by kuraiconnect** [comment]
> I am experiencing the same problem :(

You can try use fetch like me. Not cool but work 😅

I think that problem with that result is a ref. And vue can not read so deep object like this

**Comment by yepsconnect** [comment]
@Baroshem I think that I found a solution

before solution:
![Screenshot 2023-03-29 at 13 14 59](https://user-images.githubusercontent.com/125030370/228486863-8eef4756-0ebb-4c1f-b9c8-29fd413c27f1.png)

first i change apollo congifuration in `nuxt.config.ts` file. i removed `inMemoryCacheOptions` for problem endpont

![Screenshot 2023-03-29 at 12 08 20](https://user-images.githubusercontent.com/125030370/228468618-a2f1a644-1cad-4f78-b069-a9655edbaca3.png)

after that i changed options for `useQuery`
![Screenshot 2023-03-29 at 12 48 51](https://user-images.githubusercontent.com/125030370/228479811-547e4fab-66c6-4cb5-8624-1cee2a4283a4.png)

result:
![Screenshot 2023-03-29 at 13 14 35](https://user-images.githubusercontent.com/125030370/228486855-f4062f4a-72f7-4463-9669-9ccf34717483.png)

i think this problem only appears if the request has **fragments** in the body. if you disabled `addTypename: false` in apollo configuration, request will answer without **typename** and request body wich belongs that **typename**

i am not sure that it help for you, @Baroshem , but it is good for me.
