### ISSUE TITLE
Can't load .gql files after upgrading.

### ISSUE THREAD

**Issue by abattenburg** [nuxt-community/apollo-module#49]
When following the steps on the readme to upgrade to version 3.0, none of the of my .gql queries load. It instead asks me to install them manually. 

I've updated the official Nuxt example and put it in a repository that can be found [here ](https://github.com/abattenburg/Vue-Apollo-Version3.0) to show the issue. If anyone could help me fix my configuration that would be greatly appreciated. I've been waiting a few weeks for someone else to have the same problem, but so far it looks like its only me. Thanks!

**Comment by dohomi** [comment]
please read the upgrade instructions. You need to manually add your packages which are independent from this project. Mostly you might miss apollo-link-http, graphql and graphql-tag. Hope this helps

**Comment by abattenburg** [comment]
Hi @dohomi, thanks for mentioning _graph-tag_. It's not in the readme or referenced in the apollo-client upgrade doc. My reference [repo](https://github.com/abattenburg/Vue-Apollo-Version3.0/blob/master/package.json) does include _apollo-link-http_ and _graphql_ so maybe **graphql-tag** is essential and should be added to the readme?

Thanks again for the help, happy to have this working.

**Comment by dohomi** [comment]
@abattenburg added it to the README thanks for mentioning it.
