### ISSUE TITLE
Missing type definition in nuxt.config.ts

### ISSUE THREAD

**Issue by HuakunShen** [nuxt-community/apollo-module#502]
### Environment

Nuxi 3.3.3

RootDir: /Users/hacker/Desktop/nuxt-app
Nuxt project info: (copied to clipboard)

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@9.6.3`
- Builder:          `vite`
- User Config:      `modules`, `apollo`
- Runtime Modules:  `@nuxtjs/apollo@5.0.0-alpha.6`
- Build Modules:    `-`
------------------------------

### Describe the bug

I followed https://apollo.nuxtjs.org/getting-started/quick-start and installed `"@nuxtjs/apollo": "^5.0.0-alpha.6"`, but always getting error saying that `Object literal may only specify known properties, and 'apollo' does not exist in type 'NuxtConfig'.ts`

![image](https://user-images.githubusercontent.com/33727687/230585611-740452d6-ad6b-4821-8dd1-429410fb55d1.png)

### Expected behaviour

`nuxt.config.ts` should accept `apollo` config.

### Reproduction

```bash
npx nuxi init
npm i -D @nuxtjs/apollo@next
```

Fill in

```ts
import { defineNuxtConfig } from 'nuxt/config'

export default defineNuxtConfig({
  modules: ['@nuxtjs/apollo'],

  apollo: {
    clients: {
      default: {
        httpEndpoint: 'https://api.spacex.land/graphql'
      }
    },
  },
})

```

### Additional context

Reproduced on ubuntu 20.04

**Comment by slavanossar** [comment]
This was a bug in `nuxt` due to missing `@types/node` peer dependency, fixed in `3.4.0`

https://github.com/nuxt/nuxt/issues/20040

**Comment by HuakunShen** [comment]
> This was a bug in `nuxt` due to missing `@types/node` peer dependency, fixed in `3.4.0`
> 
> [nuxt/nuxt#20040](https://github.com/nuxt/nuxt/issues/20040)

Thanks!

**Comment by pagas** [comment]
Windows 11

`{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxtjs/apollo": "5.0.0-alpha.8",
    "@nuxtjs/tailwindcss": "^6.9.4",
    "@tailwindcss/typography": "^0.5.10",
    "nuxt": "^3.8.1",
    "nuxt-icon": "^0.6.1",
    "vue": "^3.3.7",
    "vue-router": "^4.2.5"
  },
  "dependencies": {
    "@headlessui/vue": "^1.7.16",
    "@heroicons/vue": "^2.0.18",
    "@nuxt/content": "^2.9.0"
  }
}
`


Still have the same issue on 3.8 nuxt.

![image](https://github.com/nuxt-modules/apollo/assets/4599148/7b0bd9ae-386f-494a-ad7f-bf8d2cd2ac1f)

**Comment by alex4506** [comment]
3.8.1 still has
