### ISSUE TITLE
How to set vue-apollo default settings (e.g. loadingKey)?

### ISSUE THREAD

**Issue by pSchaub** [nuxt-community/apollo-module#52]
How can we set the vue-apollo default settings, e.g. the `loadingKey`?
See https://github.com/Akryum/vue-apollo#advanced-options

**Comment by dohomi** [comment]
@pSchaub I guess you can do this in a plugin or middleware where you have the possibility to get the apolloProvider instance:
```
export default (context){
  const yourDefault = context.app.apolloProvider.defaultClient
  // set some defaults
}
```
This is untested I never used default values

**Comment by dohomi** [comment]
closed due to inactivity
