### ISSUE TITLE
doesnt work on newer nuxt versions

### ISSUE THREAD

**Issue by jpengelbrecht** [nuxt-community/apollo-module#541]
### Environment

just doesnt work.   the newer versions need  both these npms installed to even start up 
 "vue": "3.3.2",
 "@vue/apollo-composable": "^4.0.0-beta.8",

### Describe the bug

doesn't load on new nuxt version

### Expected behaviour

expected to work

### Reproduction

https://stackblitz.com/edit/nuxt-apollo-demo-nbfdes?file=package.json

**Comment by pschaub** [comment]
@jpengelbrecht I think this has been solved. Please try again with the latest version.
