### ISSUE TITLE
Update Vue Apollo dependency

### ISSUE THREAD

**Issue by itpropro** [nuxt-community/apollo-module#544]
Hey @Diizzayy, can you please update the Vue Apollo dependency to [v4.0.0-beta.8](https://github.com/vuejs/apollo/releases/tag/v4.0.0-beta.8)? There were a lot of fixes that are needed in some of my projects and it would be great if we don't need to overwrite the package deps.

https://github.com/nuxt-modules/apollo/blob/c93fbf0b0af2b0fcfe241d67669ad72c70d7251d/package.json#L31

**Comment by pschaub** [comment]
done, see https://github.com/nuxt-modules/apollo/commit/fee15182071d7eec77cf0930750fe6801e33e4e9
