### ISSUE TITLE
Duplicate Result of apollo query

### ISSUE THREAD

**Issue by Lahori-Jawan** [nuxt-community/apollo-module#56]
I integrated the `apollo-module` and every thing is working great but I am facing a weird problem. After I get result, I customize it to meet my need which is working just fine but Each time a `gql` query is executed, it returns the result two times which is causing the end result to appear twice. 
![2018-01-03_2144](https://user-images.githubusercontent.com/7579344/34530262-6489139a-f0d0-11e7-86ca-8c42005f8e7a.png)
as you can see that first time `posts` object is recieved, it updates the `allPosts` object but then it again gets updated to twenty and hence the duplicated result. my code is this:

```
export default {
data() {
    return {
	allPosts:[],
	charLength: 40
	}
},
apollo: {
	posts: {
	  prefetch: true,
	  query: allPosts,
	  result ({data: {posts}}) {
	    console.log('posts ', posts.length)
	    posts.forEach(post => {
	     this.allPosts.push(Object.assign({},post,{
	        body: `${post.body.substr(0, this.charLength)}...`
		}))
          });
          console.log('all-posts ', this.allPosts.length)
				}
			},
		},
		head() {
			return {title: "All posts"}
		}
	};
```
is it related to vue-apollo or nuxt? or something else?

> note: If I don't customize the result, everything works normal.

**Comment by dohomi** [comment]
@Lahori-Jawan this relates to a coding mistake: you set `this.allPosts` inside of a `forEach` loop and as result is executed multiple times you bump into this issue.
Do rather this:
```js
result({data}){
  const allPosts = data.posts
  this.allPosts = allPosts.map(v => {
   return Object.assign(
      {},
      v,
      body: `${post.body.substr(0, this.charLength)}...`
   )
 })
}
```
Be aware that through SSR and other variables result is executed multiple times

**Comment by Lahori-Jawan** [comment]
Thank you @dohomi  for the solution though its over-writing the previous which might not be what you want depending on scenario so I ended up `watch`ing the posts like this:
```
watch: {
posts() {
	this.posts.forEach(post => {
	   this.allPosts.push(Object.assign({},post,{
	      body: `${post.body.substr(0, this.charLength)}...`
	   }))
	});
   }
}
```
BTW thanks for mentioning the multiple executioning during SSR.

**Comment by dohomi** [comment]
@Lahori-Jawan up to you I won't do any watching if its not necessary. Thats why you set up the result hook which is only executed once after the data is fetched. Be aware of change detection caveats on Vue if you watch an array: https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

**Comment by Lahori-Jawan** [comment]
Thanks. I will switch to `result` hook then.
