### ISSUE TITLE
Fix context deprecations

### ISSUE THREAD

**Issue by pSchaub** [nuxt-community/apollo-module#58]
1. `context.isServer` is deprecated
```
context.isServer has been deprecated, please use process.server instead.
```

2. `context.isClient` is deprecated
```
context.isClient has been deprecated, please use process.client instead.
```

**Comment by dohomi** [comment]
Hi @pSchaub thanks for this PR. I am aware of this but as long NUXT does not publish a new version I will wait for that to be merged. Currently in RC11 your change would throw an error if I'm seeing the changes correct.

**Comment by dohomi** [comment]
Ok thanks nuxt got released today
