### ISSUE TITLE
Error in version 5.0.0-alpha.11

### ISSUE THREAD

**Issue by leisureprog** [nuxt-community/apollo-module#581]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.10.0`
- Nuxt Version:     `3.8.2`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `bun@1.0.18`
- Builder:          `-`
- User Config:      `devtools`, `app`, `modules`, `apollo`, `postcss`, `css`, `i18n`
- Runtime Modules:  `@nuxtjs/apollo@5.0.0-alpha.11`, `@nuxtjs/i18n@8.0.0-rc.11`, `@vee-validate/nuxt@4.12.3`, `@vueuse/nuxt@10.7.0`
- Build Modules:    `-`

### Describe the bug

Hello! When working with @nuxtjs/apollo I get the following error.

**Uncaught (in promise) ApolloError: token.value?.match is not a function**

### Expected behaviour

The settings were made according to the example:

https://stackblitz.com/edit/nuxt-apollo-demo

**Comment by pschaub** [comment]
@ffierce could you provide an example how to reproduce this issue on StackBlitz?
