### ISSUE TITLE
$apollo and $apolloHelpers are unknown

### ISSUE THREAD

**Issue by ibockowsky** [nuxt-community/apollo-module#588]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.9.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.6.12
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Describe the bug

<img width="377" alt="image" src="https://github.com/nuxt-modules/apollo/assets/22965136/be78375b-ce97-4a93-803c-de5da8ef6843">

It should be typed correctly

### Expected behaviour

Type should be known

### Reproduction

https://github.com/ibockowsky/nuxt3-apollo-undefined-reproduction

**Comment by ehsanonline** [comment]
I'm having the same problem with Bun and Nuxt 3.10, a workaround is:
```js
const apolloc = useApolloClient();
const apollo = useApollo();
```

**Comment by nuraeil** [comment]
@ehsanonline @ibockowsky Are you using `bundler` as resolution in `typescript\tsConfig\compilerOptions` inside of `nuxt.config.ts` or as of 3.10 natively via. Nuxt?

If so, it might be related to this one: https://github.com/nuxt-modules/apollo/issues/593

Try turning off `bundler` resolution.
