### ISSUE TITLE
How to use nuxtjs/apollo with apollo-upload-client

### ISSUE THREAD

**Issue by leisureprog** [nuxt-community/apollo-module#589]
![image](https://github.com/nuxt-modules/apollo/assets/153300677/8657d44b-0b39-48a5-813e-e59d3f55726d)

this option works, but I need websockets. How can you do it right?

**Comment by leisureprog** [comment]
![carbon](https://github.com/nuxt-modules/apollo/assets/153300677/b5254543-e19e-4769-b62b-aa396c5b1558)

**Comment by develth** [comment]
So you have to rewrite client creation to get it work?
