### ISSUE TITLE
Module '"@nuxtjs/apollo"' has no exported member 'defineApolloClient'

### ISSUE THREAD

**Issue by pixleight** [nuxt-community/apollo-module#608]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.5
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @nuxtjs/apollo@5.0.0-alpha.13
- Build Modules:    -
------------------------------

### Describe the bug

Following the documentation for configuring an Apollo Client in a its own file: https://apollo.nuxtjs.org/getting-started/configuration#clients

Importing `defineApolloClient` results in an error: 

```
Module '"@nuxtjs/apollo"' has no exported member 'defineApolloClient'.
```

### Expected behaviour

`defineApolloClient` should be available to import from `@nuxtjs/apollo`

### Reproduction

Minimal reproduction: https://stackblitz.com/edit/github-kyxu1x?file=apollo%2Fclients%2Fdefault.ts

**Comment by Diizzayy** [comment]
@pixleight this was patched in `v5.0.0-alpha.14`, the utility can now be exported as follows:
```ts
import { defineApolloClient } from '@nuxtjs/apollo/config'
```
