### ISSUE TITLE
Apollo Queries null after updating to Nuxt 1.0

### ISSUE THREAD

**Issue by abattenburg** [nuxt-community/apollo-module#62]
I'm currently using apollo-module 3.0.1.

After upgrading to Nuxt 1.0, apollo queries do not work when navigating to new pages and I get an error about queries being null. If I refresh and pull from the server however, the data does come through as expected. This is happening across multiple projects and only fails after using Nuxt 1.0. 

Has anyone else run into this issue?

**Comment by dohomi** [comment]
@abattenburg I would need a repo to help you out here. There hasn't been any breaking change of this package for the past 2-3 months. How does your configuration looks like?

**Comment by pSchaub** [comment]
@abattenburg Please provide us all your apollo configurations (client config file + nuxt.config.js configuration) and one of your failing queries so we have e better insights what exactly is failing.

**Comment by abattenburg** [comment]
Thanks for the response @dohomi and @pSchaub. Knowing that I was the only one with the issue helped me finally figure it out.

I had forgotten to include `<div v-if "Query">` at the top of all my queries. In the past versions of Nuxt this produced an error but still worked, while with Version 1.0 it fails. Happy to finally know the source of that error over these last 5 months. Thanks for the help!
