### ISSUE TITLE
Query with union

### ISSUE THREAD

**Issue by yaki4** [nuxt-community/apollo-module#70]
Hi, 
i've got a query with some union in it and i'm not quite sure how to configurate my client.
I've got a big warning that say : heuristic fragment matching going on!
Do i put my configuration for fragment in my default.js file ?

**Comment by dohomi** [comment]
@yaki4 do you use *.gql files and there you import the fragments? Do you have any sideeffects or real errors?

**Comment by yaki4** [comment]
@dohomi yup i use .gql file. For now my query's got the fragment in the same file but i plan to put it in another file. 
I've got errors when some type doesn't contains data and big warning when all my data fit my query. 

![capture d ecran 2018-01-25 a 09 01 03](https://user-images.githubusercontent.com/1856630/35392062-973de970-01ae-11e8-89a3-8e6f18eb70c7.png)

**Comment by dohomi** [comment]
@yaki4 try following: 
```
fragment.gql:
fragment zone on ZoneBaseQuery{
 id
 (...)
}

query.gql:
#import "./fragment.gql"
query someQery(..){
  yourQuery(){
    ...zone
    (...)
  }

}

```
This is how I did it without any issues yet.

**Comment by yaki4** [comment]
@dohomi : Sorry for the late response. 
I've put in place your solution but i still got the same warning for heurisitc fragment matching going on.

**Comment by dohomi** [comment]
@yaki4 do you have a repo where I could have a look? I am using fragments for long time without issues.

**Comment by yaki4** [comment]
@dohomi : You can find a repo there https://gitlab.com/yaki4/fragment-exemple
I

**Comment by yaki4** [comment]
@dohomi : I add those in hope that will fix the issue. i'll check for the default option. 
Do i have to set up the fragment matcher in my config ?

**Comment by dohomi** [comment]
@yaki4 not as far as I know, fragments should work simply like this:
```
fragment.gql
fragment client on Client{
 id
 email
 firstName
}

query.gql
#import "./fragment.gql"
query {
  Client{
    ...client
  }
}

```

**Comment by yaki4** [comment]
@dohomi Yeah it doesn't seem to be the case. I'll continue to investigate maybe i made a mistake.

**Comment by faroutchris** [comment]
@yaki4 
You need to tell apollo about all the possible types in a union type.

Simply follow the instructions here: https://www.apollographql.com/docs/react/recipes/fragment-matching.html

**Comment by yaki4** [comment]
@faroutchris: thanks for the advice.  It works now. 
I was not sure that was mandatory for union. 

Thanks @dohomi for your patience

**Comment by dohomi** [comment]
will close this issue due to inactivity. Hope you got everything sorted

**Comment by nelhop** [comment]
@yaki4 would you share how you implemented the `IntrospectionFragmentMatcher`?

Is this implemented in the `apollo-module`, or do I need to implement this manually? If latter: What would be the best practice for that?

**Comment by bswank** [comment]
@yaki4 or @faroutchris Just curious if we could get a little help as to how to go about implementing this in Nuxt.

**Comment by yaki4** [comment]
Hey @nelhop and @bswank last time i needed to use fragment was with 4.0.0-rc2.3 but i think that it's still true.
it's how i've done it: 

`
import { InMemoryCache, IntrospectionFragmentMatcher } from 'apollo-cache-inmemory'
import schema from './schema.json' <= contain schema of my graphql api
const fragmentMatcher = new IntrospectionFragmentMatcher({
    introspectionQueryResultData: schema
  })

export default ({req, app}) => {
    let headersVal = {
        'Accept-Language': app.i18n.locale
    }
    }
    return {
        httpEndpoint: 'https://mycoolgraphqlapi/api/queries',
        httpLinkOptions: {
            credentials: 'include',
            headers: headersVal
        },
        cache: new InMemoryCache({ fragmentMatcher }),
    }
}
`

**Comment by bswank** [comment]
Thank you @yaki4

**Comment by nelhop** [comment]
Thanks @yaki4.

Unfortunately I can't get it to work. 

As I apply your entries for the `default.js` config ist prompts a error: `defaultClientConfig is not a function`.

![error.png](https://cmty.s3.eu-west-1.amazonaws.com/98543958/e3c74e80-39e3-11e9-9273-371463d6e9fd.png)


My config looks like this:

`default.js`:
```
import { InMemoryCache, IntrospectionFragmentMatcher } from 'apollo-cache-inmemory'
import schema from './schema.json' 
const fragmentMatcher = new IntrospectionFragmentMatcher({
    introspectionQueryResultData: schema
  })

export default ({req, app}) => {
    return {
      httpEndpoint: 'https://mycoolgraphqlapi.com/api',
      getAuth:() => 'Bearer mytoken',
      tokenName: 'apollo-token',
      cache: new InMemoryCache({ fragmentMatcher }),
    }
}

```

`nuxt.config.js`:
```
apollo: {
  includeNodeModules: true,
  errorHandler (error) {
    console.log('%cError', 'background: red; color: white; padding: 2px 4px; border-radius: 3px; font-weight: bold;', error.message)
  },
  clientConfigs: {
    default: '@/apollo/config/default.js',
  }
},
```

Do I need to install something something or am I missing something?

**Comment by faroutchris** [comment]
@nelhop The steps to create the fragment types is explained in this link: https://www.apollographql.com/docs/react/advanced/fragments.html#fragment-matcher

You can copy and paste the code from there almost without modification.

As a high level overview of what you need to do: 
1. Query your graphql server for all possible types. 
2. Create a data structure that describes which types exist that are interfaces/unions/fragments and save that to a file (fragmentTypes.json or similar). 
3. Import and feed the data to the IntrospectionFragmentMatcher. 

Whenever your schema changes you'll need to update the fragmentTypes.json so add the query and creation of fragmentTypes.json as a step in your build process.

Not sure about your other errors though.

**Comment by nelhop** [comment]
Thanks @faroutchris, I am aware of the process. The `defaultClientConfig is not a function` error is kind of a blocker though...
I am glad for any suggestions how to fix this.

**Comment by bswank** [comment]
@nelhop Do you have a repo I can see your Nuxt project?

**Comment by nelhop** [comment]
@bswank I'll get in touch with you via email.

**Comment by nelhop** [comment]
After updating to Nuxt 2.4.5 I the defaultClientConfig is a function again. :) 

But something is still going wrong...
Now the settings from above prompt: `Cannot read property 'types' of undefined`

![Bildschirmfoto 2019-03-06 um 16.12.14.png](https://cmty.s3.eu-west-1.amazonaws.com/98543958/ab181a20-4022-11e9-ac9b-2f1e7187c18f.png)

Any Ideas on that?

**Comment by nelhop** [comment]
Solved! :)

My schema startet with `{ "data": { "__schema": {...`. After deleting `{ "data":` (and the corresponding closing `}`) it works.

**Comment by mmintel** [comment]
do you have any idea on how to generate the schema.json automatically? at the moment I have run this as a node script manually, but others may forget about this, so I would prefer to do it automatically on nuxt startup. Although I tried using an async config with nuxt-apollo which leads to some errors ( described here https://cmty.app/nuxt/apollo-module/issues/c216 )

**Comment by Alfr3d** [comment]
> Solved! :)
> 
> After updating to Nuxt 2.4.5 I the defaultClientConfig is a function again.
> 
> Another Pitfall was the syntax of the schema.json:
> My schema startet with `{ "data": { "__schema": {...`. After deleting `{ "data":` (and the corresponding closing `}`) it works.

Yes. If u don't remove "data" in the schema.json (generated from graphiQL)  throw an error :
`TypeError
Cannot read property 'types' of undefined`

**Comment by Jones-S** [comment]
> do you have any idea on how to generate the schema.json automatically? at the moment I have run this as a node script manually, but others may forget about this, so I would prefer to do it automatically on nuxt startup. Although I tried using an async config with nuxt-apollo which leads to some errors ( described here https://cmty.app/nuxt/apollo-module/issues/c216 )

I followed this guide: https://medium.com/commutatus/whats-going-on-with-the-heuristic-fragment-matcher-in-graphql-apollo-client-e721075e92be
to generate the schema.json.
Then just create a custom script in your package.json to first generate the schema.json and then start nuxt.

Something like:
(In my case I also have babel-node to help me execute the code within my schema generation file.)

```json
  "scripts": {
    "dev": "yarn build-fragments && nuxt -o",
    "build-fragment": "babel-node --presets env -- apollo/schemaQuery.js"
  },
```

**Comment by souljorje** [comment]
@yaki4, thank you, man!

**Comment by victorcngo** [comment]
this thread helped me so much, you can't imagine! thank you, folks! 🎉
