### ISSUE TITLE
How to refetch query from asyncData

### ISSUE THREAD

**Issue by lukasborawski** [nuxt-community/apollo-module#71]
So, i have some query fetching from `asyncData`:

```
aync asyncData ({ app, route, store }) {
    let id = route.params.id
    let apollo = await app.apolloProvider.defaultClient.query({
        query: directory,
        variables: {
            id: id
        },
        update: data => data.getDirById
    })
    let { data } = apollo
    const directoryObject = data.getDirById
    store.commit('SET_CURRENT_DIRECTORY', directoryObject)
},
```

after some actions in the other part of application i would like to refresh this directory, `refetch()` or calling query again from `this.$apollo` in `created` hook, doesn't work ... Any one can help?

**Comment by dohomi** [comment]
@lukasborawski if you want to use refetch() you have to use .watchQuery() and not .query(). You need to check the example on `vue-apollo` where you have the difference. In fact, if you want to have refresh/search-variables or anything else don't use asyncData, better use the default query way inside of your componoent:
```
apollo:{
  someQuery:{
    query: 'yourGqlString'
    variables(){
       // here you can watch params from your component and refetch the query
    }
  }
}
```

**Comment by dohomi** [comment]
will close this issue due to inactivity

**Comment by idesignzone** [comment]
I have the same issue. 
Vue apollo comes with a refetch function but here I can't find a way to refetch a query!
useQuery also throw an error 
`Failed to resolve import "@vue/apollo-composable"`
