### ISSUE TITLE
prefetch in apollo is dependent on async data

### ISSUE THREAD

**Issue by ralphchristianeclipse** [nuxt-community/apollo-module#78]
the problem is when i comment asyncData

prefetching seems not to work

commenting out prefetch seems to work when asyncData is not commented out any ideas?

```js
export default {
asyncData: ({ params }) => ({
    slug: params.slug,
    username: params.username
  }),
  apollo: {
    challenge: {
      query: Challenge,
      loadingKey: "loading",
      prefetch: ({ params }) => ({
        slug: params.slug
      }),
      variables() {
        return {
          slug: this.slug
        };
      },
      update: data => data.result
    },
    user: {
      query: User,
      loadingKey: "loading",
      prefetch: ({ params }) => ({
        username: params.username
      }),
      variables() {
        return {
          username: this.username
        };
      },
      update: data => data.result
    }
  }
}
```

**Comment by dohomi** [comment]
@ralphchristianeclipse sorry not sure if I understand your question correct. But this.username in variables is only available if you set asyncData. so why not doing:
```
prefetch: ({ params }) => ({
        username: params.username
      }),
      variables() {
        return {
          username: this.$route.params.username
        };
      },
```
then you don't need asyncData any longer

**Comment by ralphchristianeclipse** [comment]
Hmm so prefetch function return values are params instead of data ? 

Gonna try that out later thanks :)

**Comment by dohomi** [comment]
@ralphchristianeclipse I have no idea how the rest of your app looks like, but {params} of Nuxt is a shorthand for this.$route.params. Check out this page: https://nuxtjs.org/api/context

**Comment by ralphchristianeclipse** [comment]
@dohomi that is the problem this.$route.params.username is not available even when i do the prefetch stuff

I followed everything but it seems asyncData is really needed

**Comment by dohomi** [comment]
@ralphchristianeclipse not sure how to help you, all my queries depends on route params and I never faced this issue. Do you have a reproduction?

**Comment by ralphchristianeclipse** [comment]
@dohomi i'll create one later

**Comment by ralphchristianeclipse** [comment]
It works now i think the prefetch return variables are passed on the $route.params on nuxt
