### ISSUE TITLE
Accessing middleware in Vuex

### ISSUE THREAD

**Issue by abattenburg** [nuxt-community/apollo-module#79]
I know this has been covered previously (#5 for instance), but what is the current best practice to access tokens set in middleware? Using the readme example for creating middleware, how do I access the token? For instance in:

```
export default (ctx) => {
  const httpLink = new HttpLink({ uri: 'http://localhost:8000/graphql' })

  // auth token
  let token = process.server ? ctx.req.session : window.__NUXT__.state.session

  // middleware
  const middlewareLink = new ApolloLink((operation, forward) => {
    operation.setContext({
      headers: { authorization: `Bearer ${token}` }
    })
    return forward(operation)
  })
  const link = middlewareLink.concat(httpLink)
  return {
    link,
    cache: new InMemoryCache()
  }
}
```

Should I still access the token with req.session like below? I
```
export const state = () => ({
  authUser: null
})

export const mutations = {
  SET_USER: function (state, user) {
    state.authUser = user
  }
}

export const actions = {
  nuxtServerInit({ commit }, { req }) {
    if (req.session) {
      commit('SET_USER', req.session)
    }
  }
}
```

Or with Apolo Module 3 is their now a new way of accessing the token? When I console.log the context of the app, I can't find a place for the req.session which makes sense because we are no longer setting anything to it.

I know this is a basic question but their is nothing in the Readme about actually accessing the middleware. Any suggestions are greatly appreciated!

**Comment by dohomi** [comment]
@abattenburg you can try using a middleware like this:
```
export default (ctx){
  if(ctx.isServer){
    ctx.store.dispatch('user',ctx.req.session)
   }else{
     // user token on client
     console.log(ctx.store.state.user)
   }
}
```

**Comment by kieusonlam** [comment]
@abattenburg I think I know what are you missing. I have a little confuse about this at the begining too. With Nuxt you have to care about both about client side and server side, `req.session` is only exist on server side. Then if you console.log the `context` you should see it on the terminal  (where you run your project), not in the browser. If the terminal also not exist, it just because you just did not set it yet.

For me, I use express-session and axios to set the token on `req.session`, something like this
https://nuxtjs.org/examples/auth-routes

with a little tweaks
```
router.post('/login', (req, res) => {
  const token = req.body.token
  if (token) {
    req.session.authToken = token
    return res.json({ token })
  }
  res.status(401).json({ message: 'Bad credentials' })
})

router.post('/logout', (req, res) => {
  delete req.session.authToken
  res.json({ ok: true })
})
```
my login component
```
async emailLogin () {
      this.$apollo.mutate({
        mutation: UserLogin,
        variables: {
          email,
          password
        }
      }).then((result) => {
        const token = result.data.login.token
        this.$axios.post('/login', { id, token })
      }).catch((error) => {
        console.log(error)
      })
}
```
This maybe not the best way to do it, but that what I use to handle on server side token.

To set token to on client side it a bit more confuse on nuxt. I can comfirm that `window.__NUXT__.state.session` is not working and you also cannot define Vue instance to use in the context. You may find a solution on https://github.com/nuxt-community/apollo-module/issues/73

**Comment by abattenburg** [comment]
Thank you @dohomi that all makes sense, but how do I set my cookie to ctx.req.session? If I set the cookie directly in the default.js to ctx.req.session it breaks the rest of my app. Do i need to use express to do it and set to a field like `ctx.req.session.authToken` Like @kieusonlam recommends? Again I've tried setting my token to `ctx.req.session.authToken` directly with no luck.

This line `let token = process.server ? ctx.req.session : window.__NUXT__.state.session` in particular confuses me because the `ctx.req.session` is filled with something that I can't overwrite with my token, and with `window.__NUXT__.state.session` why are we not just accessing the state directly if it is the client side?

For the last few months I've been managing auth by extracting the cookie on every page individually but that obviously doesn't seem like a great solution. I'm fine with using express, it just seems overkill since I already have my token and the user authenticated. Again thank you both for the help, I've been uncertain how to approach and looked at it many times.

**Comment by abattenburg** [comment]
As an update I ended up avoiding everything concerning `ctx.req.session` and just went back to my old implementation. I check for the cookie (the nuxt auth module is good for catching all edge cases around Cookies and grabbing them), and then I access the token in vuex via the `nuxtServerInit` method.

I'm sure i'm missing some edge cases, but it's been working so far. Thank you both again for helping explain everything to me!
