### ISSUE TITLE
Update vue-apollo beta

### ISSUE THREAD

**Issue by dohomi** [nuxt-community/apollo-module#80]
Update codebase to `vue-apollo` beta.1

@Akryum could you point me to the right direction what changes needs to be make? I tried to update to beta.1 without success. If I call apolloProvider.provide() then `prefetchAll` is not a function. I might misunderstand your upgrade guide. Thanks

**Comment by Akryum** [comment]
You just need to change the line in the options of `new Vue({..})`. See [this example](https://github.com/Akryum/vue-apollo#creating-the-apollo-clients)

**Comment by dohomi** [comment]
@Akryum not sure where to look at. I tried changing
```
app.apolloProvider = new VueApollo(providerOptions)

=> to
const apolloProvider = new VueApollo(providerOptions)
app.apolloProvider = apolloProvider.provide()
```
But that results into undefined code.

**Comment by dohomi** [comment]
As we don't make use of `new Vue(...)` I'm not sure how to make this work with `Nuxt`. @Atinux could you have a look at this? Thanks

**Comment by pSchaub** [comment]
Same issue here. How can we fix this?
