### ISSUE TITLE
DateTime in query variable

### ISSUE THREAD

**Issue by morriq** [nuxt-community/apollo-module#88]
Hello,

I have query

```
apollo: {
      allChannels: {
        query: allChannels,
        update: (data) => data.allChannels,
        prefetch: true,
        variables: () => ({
          first: 3,
          lastActivity
        })
      }
    }
```

where `lastActivity = new Date().toISOString()` (for example)

That way my component is refreshing data on client side. When I create `lastActivity = "2016-02-20T18:21:41.375Z"`  then it's fine - it's not refreshing content. 
I don't want to refresh data on client side but I want to have posibility to put currentTime (lets say serverside date is enough) in query. How could I achieve that?

**Comment by dohomi** [comment]
@morriq maybe use 
```
prefetch(){
  return {
   first:3,
   lastActivity
  }
}
```
to ensure that SSR and client has the exact same set on data. Skipping your query is done via the 
```
skip(){
  return lastActivity <= new Date().toISOString()
}
```
Hope this helps. Beside that, you might better check vue-apollo docs or apollo itself. This package is a simple wrap to make it easy to use with Nuxt but doesn't do any magic with your queries

**Comment by morriq** [comment]
Without luck with skiping, thank you for help. I'm going to ask on vue-apollo.
Thanks!

**Comment by Akryum** [comment]
If you have the same exact variables on the server and on the client, it will get results from the cache. Also, the queries are skipped for a certain amount of time while the app is re-hydrated on the client.

**Comment by Akryum** [comment]
Also, make sure this component is directly used in a route (`{ path: '/foo', component: ThisComponent }`) or use [willPrefetch](https://github.com/Akryum/vue-apollo#prefetch-components).
