### ISSUE TITLE
Access store for dynamic URI

### ISSUE THREAD

**Issue by yaki4** [nuxt-community/apollo-module#89]
I need to create a dynamic graphql client for a project and i want to access my store to put some params in my uri. 

I've tried to access my store  like this but it doesn't work : 
if (process.server) {
    console.log(ctx.req.store)
  } else {
    console.log(ctx.store.app.store.state.gps)
    console.log(window.__NUXT__.state.value)
  } 

Is it better to pass by the localStorage for a dynamic uri ?

**Comment by dohomi** [comment]
@yaki4 can you show me how your config file looks like?

**Comment by yaki4** [comment]
You can find my configuration for my apollo client below. 
The schema.json file contain the schema of my database to prevent fragment issue. 
import { ApolloLink } from 'apollo-link'
import { HttpLink } from 'apollo-link-http'
import { InMemoryCache, IntrospectionFragmentMatcher } from 'apollo-cache-inmemory'
import schema from './schema.json'
export default (ctx, store) => {
  console.log('vonjour le contexte', store)
  console.log('le store', store)
  if (process.server) {
    console.log(ctx.req.store)
  } else {
    console.log(ctx.store.app.store.state.gps)
    console.log(window.__NUXT__.state.value)
    let httpLink = new HttpLink({ uri: 'https://xxxx.xyz/api/v1/graphql?locale=fr&lat=' ctx.store.app.store.state.gps'&lng=' ctx.store.app.store.state.gps, credentials: 'include' })
  }

  // auth token
  let token = process.server ? ctx.req.session : window.__NUXT__.state.session
  const fragmentMatcher = new IntrospectionFragmentMatcher({
    introspectionQueryResultData: schema
  })
  // middleware
  const middlewareLink = new ApolloLink((operation, forward) => {
    operation.setContext({
      headers: { authorization: `Bearer ${token}` }
    })
    return forward(operation)
  })
  const link = middlewareLink.concat(httpLink)
  return {
    link,
    cache: new InMemoryCache({ fragmentMatcher })
  }
}

**Comment by yaki4** [comment]
I forgot to put my store configuration. 
import Vuex from 'vuex'
import mutations from './mutations'

const createStore = () => {
  return new Vuex.Store({
    state: {
      gps: {lat: null, lng: null}
    },
    mutations
  })
}

and for mutations i've got 
const mutations = {
  set_gps (state, gps) {
    console.log('valeur de state', state)
    console.log('valeur pour mutation', gps)
    state.gps = gps
    // state.gps.lat = gps.lat
    // state.gps.lng = gps.lng
  }
}

export default mutations

**Comment by dohomi** [comment]
@yaki4 you need to move your code into the function of the middleware. Beside that you don't do the right thing with the context, I'll correct your config quick:
```javascript
import { ApolloLink } from 'apollo-link'
import { HttpLink } from 'apollo-link-http'
import { InMemoryCache, IntrospectionFragmentMatcher } from 'apollo-cache-inmemory'
import schema from './schema.json'
export default ({store,req}) => {
  let httpLink = new HttpLink({ uri: 'https://xxxx.xyz/api/v1/graphql?locale=fr&lat=' store.state.gps'&lng=' store.state.gps, credentials: 'include' })
  
  const fragmentMatcher = new IntrospectionFragmentMatcher({
    introspectionQueryResultData: schema
  })
  // middleware
  const middlewareLink = new ApolloLink((operation, forward) => {
    // auth token
    let token = process.server ? req.session : store.state.session
    console.log(process.env.server, store.state)
   
    operation.setContext({
      headers: { authorization: `Bearer ${token}` }
    })
    return forward(operation)
  })
  const link = middlewareLink.concat(httpLink)
  return {
    link,
    cache: new InMemoryCache({ fragmentMatcher })
  }
}
```
Hope this gives you an idea how to finalize your setup

**Comment by yaki4** [comment]
Hi thanks once again Dohomi for your help.

This issue can be closed now.

**Comment by dohomi** [comment]
great news.
