### ISSUE TITLE
Store rehydration

### ISSUE THREAD

**Issue by esindger** [nuxt-community/apollo-module#90]
Hello,

As I see the plugin restore state from `window.__NUXT__.apollo.defaultClient`:
https://github.com/nuxt-community/apollo-module/blob/master/plugin.js#L33

 But it's not clear to me how to extract the state from the server. The `window.__NUXT__.apollo.defaultClient` object is always emty after server rendering.  Can you provide an example how to rehydrate apollo state? 

Thank you.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/apollo-module/issues/c66">#c66</a>)</em></sub></div>

**Comment by dohomi** [comment]
@esindger what are you trying to do? You should not think too much about how the rehydration works. If you want to access apollo check out the usage examples: https://github.com/nuxt-community/apollo-module#usage

**Comment by esindger** [comment]
@dohomi,
During initialization all graphql requests are performing twice. First time it happens from the server and then, second time, from the client. I want to pass initial state from server to client in order to avoid overhead requests.

I thought the rehydration is authomatic but it's not true. 

> If you want to access apollo check out the usage examples: https://github.com/nuxt-community/apollo-module#usage

I saw that examples but still no have an idea how to extracts server state in my apollo config.
I hope you have any thoughts. Thank you

**Comment by dohomi** [comment]
@esindger without any repo or code example to visualize what you trying to archive I won't be able to help. 

Apollo will always trigger multiple times but uses an internal cache which data is declared as fetched and which one will update the internal store state. So don't worry about that, if you use this module you don't need to think too much how often internally apollo is being called.

You get your store state if you request it from the module context:

```
export default ({store}) {
 // store is initialized and fetch on server and on client again
}
```

**Comment by dohomi** [comment]
I close this issue due to inactivity
