### ISSUE TITLE
"Variable x was not provided" even if it is correctly passed

### ISSUE THREAD

**Issue by Hurtak** [nuxt-community/apollo-module#91]
We are using nuxtjs/apollo: "3.0.4" with latest apollo. And when making query with variables sometimes it is not reckognized (`Variable "$userId" of required type "String!" was not provided.`) even if we pass it in correctly, but this only happens when we use websocket connection, if we switch to HTTP it works fine.

What I also encountered on different ocasion is that the query worked when i did server side render, but when i transitioned to that page on the client it told me the variable not provided error.

More info in https://github.com/apollographql/apollo-client/issues/3060

**Comment by dohomi** [comment]
@Hurtak without any code or repo I'd not be able to help. I suspect you are not publishing the userId correctly on both client and server side
