### ISSUE TITLE
How to access the client in nuxt.config.js?

### ISSUE THREAD

**Issue by PZ01** [nuxt-community/apollo-module#92]
When generating a website, dynamic routes can be generated by calling an end-point using [Axios](https://nuxtjs.org/api/configuration-generate).

Is there a way to get a reference to the Apollo client to do something equivalent? Someone raised the issue on the [nuxt page](https://github.com/nuxt/nuxt.js/issues/2254).

My only alternative is to create webhooks on the GraphQL server and simply fetch them in a Restful matter.

**Comment by PZ01** [comment]
I got it done using Apollo-Fetch instead. It's good enough for this use-case.
```
const { createApolloFetch } = require('apollo-fetch');
...
{
        routes: function () {
            const staticRoutes = [
            ];

            const GRAPHCMS_API = 'URL';
            const apolloFetch = createApolloFetch({ uri: GRAPHCMS_API })
            const query = `
            query allPostIdentifiers {
                posts:allPosts {
                    id
                    slug
                }
                tags:allTags {
                    name
                }
            }
            `;

            return apolloFetch({ query }) // all apolloFetch arguments are optional 
                .then(result => {

                    const { data } = result
                    const postRoutes = data.posts.map(post => `/posts/${post.slug}?id=${post.id}`);
                    const tagRoutes =   data.tags.map(tag => `/tags/${tag.name}`);

                    return staticRoutes.concat([...postRoutes, ...tagRoutes]);
                })
                .catch(error => {
                    console.log('got error')
                    console.log(error)
                })
        }
    }
```

**Comment by mmintel** [comment]
I would still like to know if this is possible.

**Comment by jcfinnerup** [comment]
Me too 👍

**Comment by adamchipperfield** [comment]
This would be insanely helpful. Especially with the ability to pass payloads. I want to make all of my queries up front as I dynamically fetch the routes.

Ideally I want to keep the gql files I already have and pass everything through the same Apollo client. Has anyone done this?

**Comment by this-is-fine-dev** [comment]
bump
