### ISSUE TITLE
Credentials from another domain get delete when refresh

### ISSUE THREAD

**Issue by yaki4** [nuxt-community/apollo-module#95]
I've set up my clients credentials to include and it works perfectly fine. 
But when i reload my page this credentials are deleted from my cookies.
I've see some package like apollo-cache-persist but i'm not sure that it's the right stuff for my use case.
Is there a way to keep theses information ?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/apollo-module/issues/c68">#c68</a>)</em></sub></div>

**Comment by dohomi** [comment]
@yaki4 this package does not modify your cookies. the issue seems to belong in how you set-reset the cookies in your application code. Probably move to the official Nuxt package to seek for the information there.

`apollo-cache-persist` might be an alternative but I never used it so far.

**Comment by dohomi** [comment]
I close this issue due to inactivity.
