### ISSUE TITLE
Not possible to write clients with ES5 syntax

### ISSUE THREAD

**Issue by moltar** [nuxt-community/apollo-module#96]
Using `require` is not possible in the client, which prevents me from writing tests without using babel. I think it is because the plugin is using ES6 syntax and two do not mix.

Is it possible to write the plugin in ES5 syntax?

Or any other suggestions to fix this besides installing `babel-cli` just for one test case?

Thanks.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/apollo-module/issues/c70">#c70</a>)</em></sub></div>

**Comment by dohomi** [comment]
@moltar this plugin is a superset of Nuxt where you write in es6 syntax. Not sure why you can't import modules with the require syntax, I do that quite often.

**Comment by moltar** [comment]
I am talking in a context of a unit test. I cannot require this module with import statements without transpiling it first.

**Comment by dohomi** [comment]
@moltar did you try to use AVA for testing? That is what I use for my tests in general, there ES6 is running out of the box. I don't plan to change the concept of how this module is included for each Nuxt project.

**Comment by dohomi** [comment]
@moltar v4 provides a new way to wire up your apollo-config. I am closing this issue now as there has been too many changes internally and hopefully with AVA tests everything should work
