### ISSUE TITLE
Prefetch does not work or there is no correct docs about it

### ISSUE THREAD

**Issue by samirph** [nuxt-community/apollo-module#99]
As there is no example of how to use `prefetch` in this repository, I followed the example at https://github.com/Akryum/vue-apollo

So it looks like this:
```
apollo: {
    travel_type: {
      query: gql`
      query travel_type($id: Int){
        travel_type (id: $id) {
          id
          name
        }
      }`,
      prefetch: ({ route }) => {
        return {
          id: route.params.id
        }
      },
      variables: {
        id: this.id
      }
    }
  }
```
It does not work. The variables field in the graphql request is an empty object.

**Comment by adamkhan** [comment]
I am having the same issue.

**Comment by dmrz** [comment]
Why is it closed? I think this is still an issue. Any updates?

**Comment by dohomi** [comment]
@dmrz I meant use asyncData or fetch like this:
```js
async asyncData({app}){
  const {data} = app.apolloProvider.defaultClient.query({query,variables})
  return {
   travels: data.allTravels
  }
}
```

**Comment by samirph** [comment]
I'm still calling my apollo query after the page is created so the route parameters are already accessible.
Gonna try using prefetch again based on the example above or just update this dependency and see if it's fixed.

**Comment by adamkhan** [comment]
@samirph I hadn't realized this is not working server-side and is being rendered client-side, but viewing source, yes, there's nothing there. So I hope you can get this working. Haven't tried @dohomi's suggestion to use asyncData

**Comment by dohomi** [comment]
@samirph try following:
```
prefetch: ({ route }) => {
       return {
         mode: route.name
       }
     },
     variables(){
       return {mode: this.$route.name === 'agency-proposals' ? 'all' : 'travel_agency_user'}
     }
```
You have to return the exact same arguments on prefetch and variables.

**Comment by adamkhan** [comment]
@samirph and @dohomi, this works for me. Thank you very much, I have content upon initial load of my pages!
